//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SellingWS.Resources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario no tiene autorización o la contraseña es incorrecta..
        /// </summary>
        internal static string AjusteInventario_Autenticacion_Error {
            get {
                return ResourceManager.GetString("AjusteInventario_Autenticacion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no existe..
        /// </summary>
        internal static string AjusteInventario_Producto_NotFound {
            get {
                return ResourceManager.GetString("AjusteInventario_Producto_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible realizar ajustes a una Ubicación que tiene Material bloqueado o apartado..
        /// </summary>
        internal static string AjusteInventario_Ubicacion_ApartadoBloqueado {
            get {
                return ResourceManager.GetString("AjusteInventario_Ubicacion_ApartadoBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación tiene que ser de tipo Stage o Almacenaje..
        /// </summary>
        internal static string AjusteInventario_Ubicacion_NoContent {
            get {
                return ResourceManager.GetString("AjusteInventario_Ubicacion_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no existe..
        /// </summary>
        internal static string AjusteInventario_Ubicacion_NotFound {
            get {
                return ResourceManager.GetString("AjusteInventario_Ubicacion_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad debe ser mayor a 0..
        /// </summary>
        internal static string Almacenaje_Cantidad_Incorrecta {
            get {
                return ResourceManager.GetString("Almacenaje_Cantidad_Incorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Estrategia para la Ubicación de Almacenaje seleccionada está asignada a un Material distinto..
        /// </summary>
        internal static string Almacenaje_Estrategia_DiferenteProducto {
            get {
                return ResourceManager.GetString("Almacenaje_Estrategia_DiferenteProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra Estrategia de colocación para este Material..
        /// </summary>
        internal static string Almacenaje_Estrategia_NotFound {
            get {
                return ResourceManager.GetString("Almacenaje_Estrategia_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de Material a mover es mayor a la disponible en la Ubicación..
        /// </summary>
        internal static string Almacenaje_Producto_NoContent4 {
            get {
                return ResourceManager.GetString("Almacenaje_Producto_NoContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no existe en la Ubicación..
        /// </summary>
        internal static string Almacenaje_Producto_NotFound {
            get {
                return ResourceManager.GetString("Almacenaje_Producto_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intenta con una cantidad menor. Puede mover únicamente {0} materiales a esa ubicación..
        /// </summary>
        internal static string Almacenaje_ProductoCantidad_Destino_NotFound {
            get {
                return ResourceManager.GetString("Almacenaje_ProductoCantidad_Destino_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intenta con una cantidad menor. Hay disponibles únicamente {0}..
        /// </summary>
        internal static string Almacenaje_ProductoCantidad_Origen_NotFound {
            get {
                return ResourceManager.GetString("Almacenaje_ProductoCantidad_Origen_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación debe ser tipo Stage o Tránsito..
        /// </summary>
        internal static string Almacenaje_Ubicacion_NoContent {
            get {
                return ResourceManager.GetString("Almacenaje_Ubicacion_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación está bloqueada..
        /// </summary>
        internal static string Almacenaje_Ubicacion_NoContent2 {
            get {
                return ResourceManager.GetString("Almacenaje_Ubicacion_NoContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación es tipo Stage pero el Material no está disponible..
        /// </summary>
        internal static string Almacenaje_Ubicacion_NoContent3 {
            get {
                return ResourceManager.GetString("Almacenaje_Ubicacion_NoContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material está bloqueado y la Ubicación no es de Tránsito.
        /// </summary>
        internal static string Almacenaje_Ubicacion_NoContent4 {
            get {
                return ResourceManager.GetString("Almacenaje_Ubicacion_NoContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no existe..
        /// </summary>
        internal static string Almacenaje_Ubicacion_NotFound {
            get {
                return ResourceManager.GetString("Almacenaje_Ubicacion_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación de Almacenaje seleccionada no tiene volumen disponible, intente con una Cantidad menor o una Ubicación distinta..
        /// </summary>
        internal static string Almacenaje_Ubicacion_SobrepasaVolumen {
            get {
                return ResourceManager.GetString("Almacenaje_Ubicacion_SobrepasaVolumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación de Almacenaje está Bloqueada..
        /// </summary>
        internal static string Almacenaje_UbicacionAlmacenaje_Bloqueada {
            get {
                return ResourceManager.GetString("Almacenaje_UbicacionAlmacenaje_Bloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación de Almacenaje no contiene Materiales de la misma Familia..
        /// </summary>
        internal static string Almacenaje_UbicacionAlmacenaje_DiferenteGrupo {
            get {
                return ResourceManager.GetString("Almacenaje_UbicacionAlmacenaje_DiferenteGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra la Ubicación de Almacenaje..
        /// </summary>
        internal static string Almacenaje_UbicacionAlmacenaje_NotFound {
            get {
                return ResourceManager.GetString("Almacenaje_UbicacionAlmacenaje_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra la Ubicación de Tránsito..
        /// </summary>
        internal static string Almacenaje_UbicacionTransito_NotFound {
            get {
                return ResourceManager.GetString("Almacenaje_UbicacionTransito_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no está disponible para un cambio de estado en la Ubicación..
        /// </summary>
        internal static string CambioEstado_Material_NoContent {
            get {
                return ResourceManager.GetString("CambioEstado_Material_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no existe en la Ubicación..
        /// </summary>
        internal static string CambioEstado_Material_NotFound {
            get {
                return ResourceManager.GetString("CambioEstado_Material_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las Ubicaciones de Tránsito no son válidas para operaciones de Cambio de Estado..
        /// </summary>
        internal static string CambioEstado_Ubicacion_NoContent {
            get {
                return ResourceManager.GetString("CambioEstado_Ubicacion_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no existe..
        /// </summary>
        internal static string CambioEstado_Ubicacion_NotFound {
            get {
                return ResourceManager.GetString("CambioEstado_Ubicacion_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no existe o el Material no existe en esa Ubicación..
        /// </summary>
        internal static string CambioEstado_Ubicacion_NotFound2 {
            get {
                return ResourceManager.GetString("CambioEstado_Ubicacion_NotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, algo salio mal..
        /// </summary>
        internal static string General_Error {
            get {
                return ResourceManager.GetString("General_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Producto solo Permite {0} decimal(es)..
        /// </summary>
        internal static string General_Mayor_Decimales {
            get {
                return ResourceManager.GetString("General_Mayor_Decimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto no acepta decimales..
        /// </summary>
        internal static string General_No_Decimales {
            get {
                return ResourceManager.GetString("General_No_Decimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problema de Autenticación, intente iniciar sesión nuevamente..
        /// </summary>
        internal static string General_Token_NotFound {
            get {
                return ResourceManager.GetString("General_Token_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un problema con la identificación del usuario..
        /// </summary>
        internal static string General_USRClave_NotFound {
            get {
                return ResourceManager.GetString("General_USRClave_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad debe ser mayor o igual a 0..
        /// </summary>
        internal static string Recibo_Cantidad_Incorrecta {
            get {
                return ResourceManager.GetString("Recibo_Cantidad_Incorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra Estrategia de colocación para este Material..
        /// </summary>
        internal static string Recibo_Estrategia_NotFound {
            get {
                return ResourceManager.GetString("Recibo_Estrategia_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró alguna Estructura de Tránsito en ese Almacén..
        /// </summary>
        internal static string Recibo_EstructuraTransito_NotFound {
            get {
                return ResourceManager.GetString("Recibo_EstructuraTransito_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra ese Id de Recibo..
        /// </summary>
        internal static string Recibo_IdRecibo_NotFound {
            get {
                return ResourceManager.GetString("Recibo_IdRecibo_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de Material leída excede a la cantidad solicitada..
        /// </summary>
        internal static string Recibo_Material_Excedente {
            get {
                return ResourceManager.GetString("Recibo_Material_Excedente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al registrar el sobrante, queda prueba en el archivo de Log..
        /// </summary>
        internal static string Recibo_Material_Excedente_Error {
            get {
                return ResourceManager.GetString("Recibo_Material_Excedente_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no existe en la Ubicación..
        /// </summary>
        internal static string Recibo_Material_NotFound {
            get {
                return ResourceManager.GetString("Recibo_Material_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Motivo no es válido..
        /// </summary>
        internal static string Recibo_Producto_MotivoSobrante_NotFound {
            get {
                return ResourceManager.GetString("Recibo_Producto_MotivoSobrante_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no existe..
        /// </summary>
        internal static string Recibo_Producto_NotFound {
            get {
                return ResourceManager.GetString("Recibo_Producto_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra ese Registro de Sobrante..
        /// </summary>
        internal static string Recibo_Producto_ReciboSobrante_NotFound {
            get {
                return ResourceManager.GetString("Recibo_Producto_ReciboSobrante_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede colocar el Material en esa  ubicación, intente con la lectura de una diferente..
        /// </summary>
        internal static string Recibo_Ubicacion_NoArea {
            get {
                return ResourceManager.GetString("Recibo_Ubicacion_NoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la Ubicación..
        /// </summary>
        internal static string Recibo_Ubicacion_NoContent {
            get {
                return ResourceManager.GetString("Recibo_Ubicacion_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no existe..
        /// </summary>
        internal static string Recibo_Ubicacion_NotFound {
            get {
                return ResourceManager.GetString("Recibo_Ubicacion_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no es de Tránsito..
        /// </summary>
        internal static string Recibo_Ubicacion_NoTransito {
            get {
                return ResourceManager.GetString("Recibo_Ubicacion_NoTransito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no existe en la Ubicación..
        /// </summary>
        internal static string Reubicacion_Material_NotFound {
            get {
                return ResourceManager.GetString("Reubicacion_Material_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación de destino no puede ser de tipo Tránsito o Andén..
        /// </summary>
        internal static string Reubicacion_UbicacionDestino_NoContent {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionDestino_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no pertenece a la misma Familia que los Materiales de la Ubicación destino..
        /// </summary>
        internal static string Reubicacion_UbicacionDestino_NoContent2 {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionDestino_NoContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no está disponible para una Reubicación..
        /// </summary>
        internal static string Reubicacion_UbicacionDestino_NoContent3 {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionDestino_NoContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación destino no tiene espacio disponible..
        /// </summary>
        internal static string Reubicacion_UbicacionDestino_NoContent4 {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionDestino_NoContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Material no tiene la misma Área de Estrategia que la Ubicación destino..
        /// </summary>
        internal static string Reubicacion_UbicacionDestino_NoContent5 {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionDestino_NoContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación de destino no existe..
        /// </summary>
        internal static string Reubicacion_UbicacionDestino_NotFound {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionDestino_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo se permiten Ubicaciones tipo Stage o Almacenaje..
        /// </summary>
        internal static string Reubicacion_UbicacionOrigen_NoContent {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionOrigen_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no existe..
        /// </summary>
        internal static string Reubicacion_UbicacionOrigen_NotFound {
            get {
                return ResourceManager.GetString("Reubicacion_UbicacionOrigen_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un Almacen..
        /// </summary>
        internal static string Surtido_ALMClave_Empty {
            get {
                return ResourceManager.GetString("Surtido_ALMClave_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar por lo menos un Área..
        /// </summary>
        internal static string Surtido_AREClaves_Empty {
            get {
                return ResourceManager.GetString("Surtido_AREClaves_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento actual se encuentra asignado a otro usuario..
        /// </summary>
        internal static string Surtido_Asignado {
            get {
                return ResourceManager.GetString("Surtido_Asignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La versión del movil no es igual a la que esta registrada..
        /// </summary>
        internal static string Token_Version_Error {
            get {
                return ResourceManager.GetString("Token_Version_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ubicación se encuentra en proceso de almacenaje.
        /// </summary>
        internal static string Ubicacion_Proceso_Almacenaje {
            get {
                return ResourceManager.GetString("Ubicacion_Proceso_Almacenaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ubicación de tipo transito se encuentra en proceso de recibo.
        /// </summary>
        internal static string Ubicacion_Transito_Utilizado {
            get {
                return ResourceManager.GetString("Ubicacion_Transito_Utilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ubicación actual está siendo utilizada en un Recibo diferente.
        /// </summary>
        internal static string Ubicacion_Utilizada {
            get {
                return ResourceManager.GetString("Ubicacion_Utilizada", resourceCulture);
            }
        }
    }
}
