'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FormasDigitales
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://wservicios/", ConfigurationName:="FormasDigitales.WSTimbradoCFDI")>  _
    Public Interface WSTimbradoCFDI
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/Cancelacion_2Request", ReplyAction:="http://wservicios/WSTimbradoCFDI/Cancelacion_2Response"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cancelacion_2(ByVal request As FormasDigitales.Cancelacion_2Request) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FormasDigitales.Cancelacion_2Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/Cancelacion_2Request", ReplyAction:="http://wservicios/WSTimbradoCFDI/Cancelacion_2Response")>  _
        Function Cancelacion_2Async(ByVal request As FormasDigitales.Cancelacion_2Request) As System.Threading.Tasks.Task(Of FormasDigitales.Cancelacion_2Response)
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/Cancelacion_1Request", ReplyAction:="http://wservicios/WSTimbradoCFDI/Cancelacion_1Response"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cancelacion_1(ByVal request As FormasDigitales.Cancelacion_1Request) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FormasDigitales.Cancelacion_1Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/Cancelacion_1Request", ReplyAction:="http://wservicios/WSTimbradoCFDI/Cancelacion_1Response")>  _
        Function Cancelacion_1Async(ByVal request As FormasDigitales.Cancelacion_1Request) As System.Threading.Tasks.Task(Of FormasDigitales.Cancelacion_1Response)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/TimbrarZipRequest", ReplyAction:="http://wservicios/WSTimbradoCFDI/TimbrarZipResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TimbrarZip(ByVal request As FormasDigitales.TimbrarZipRequest) As FormasDigitales.TimbrarZipResponse
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/TimbrarZipRequest", ReplyAction:="http://wservicios/WSTimbradoCFDI/TimbrarZipResponse")>  _
        Function TimbrarZipAsync(ByVal request As FormasDigitales.TimbrarZipRequest) As System.Threading.Tasks.Task(Of FormasDigitales.TimbrarZipResponse)
        
        'CODEGEN: El parámetro 'acuseCFDI' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/TimbrarCFDIRequest", ReplyAction:="http://wservicios/WSTimbradoCFDI/TimbrarCFDIResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TimbrarCFDI(ByVal request As FormasDigitales.TimbrarCFDIRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="acuseCFDI")> FormasDigitales.TimbrarCFDIResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://wservicios/WSTimbradoCFDI/TimbrarCFDIRequest", ReplyAction:="http://wservicios/WSTimbradoCFDI/TimbrarCFDIResponse")>  _
        Function TimbrarCFDIAsync(ByVal request As FormasDigitales.TimbrarCFDIRequest) As System.Threading.Tasks.Task(Of FormasDigitales.TimbrarCFDIResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private signedInfoField As SignedInfoType
        
        Private signatureValueField() As Byte
        
        Private keyInfoField As KeyInfoType
        
        Private objectField() As ObjectType
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = value
                Me.RaisePropertyChanged("SignedInfo")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=1)>  _
        Public Property SignatureValue() As Byte()
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = value
                Me.RaisePropertyChanged("SignatureValue")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = value
                Me.RaisePropertyChanged("KeyInfo")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Object", Order:=3)>  _
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set
                Me.objectField = value
                Me.RaisePropertyChanged("Object")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignedInfoType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private canonicalizationMethodField As CanonicalizationMethodType
        
        Private signatureMethodField As SignatureMethodType
        
        Private referenceField As ReferenceType
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = value
                Me.RaisePropertyChanged("CanonicalizationMethod")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = value
                Me.RaisePropertyChanged("SignatureMethod")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Reference() As ReferenceType
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
                Me.RaisePropertyChanged("Reference")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class CanonicalizationMethodType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class acuseCFDI
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoErrorField As String
        
        Private errorField As String
        
        Private xmlTimbradoField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoError() As String
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
                Me.RaisePropertyChanged("codigoError")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
                Me.RaisePropertyChanged("error")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property xmlTimbrado() As String
            Get
                Return Me.xmlTimbradoField
            End Get
            Set
                Me.xmlTimbradoField = value
                Me.RaisePropertyChanged("xmlTimbrado")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class acuseZip
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private errorField As String
        
        Private nombrexmlField As String
        
        Private uuidField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
                Me.RaisePropertyChanged("error")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property nombrexml() As String
            Get
                Return Me.nombrexmlField
            End Get
            Set
                Me.nombrexmlField = value
                Me.RaisePropertyChanged("nombrexml")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("uuid")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class acuseRecepcionZip
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoErrorField As String
        
        Private errorField As String
        
        Private listaCFDIsField() As acuseZip
        
        Private nombrezipField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoError() As String
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
                Me.RaisePropertyChanged("codigoError")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
                Me.RaisePropertyChanged("error")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("listaCFDIs", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property listaCFDIs() As acuseZip()
            Get
                Return Me.listaCFDIsField
            End Get
            Set
                Me.listaCFDIsField = value
                Me.RaisePropertyChanged("listaCFDIs")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property nombrezip() As String
            Get
                Return Me.nombrezipField
            End Get
            Set
                Me.nombrezipField = value
                Me.RaisePropertyChanged("nombrezip")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class folio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estatusUUIDField As String
        
        Private mensajeField As String
        
        Private uuidField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property estatusUUID() As String
            Get
                Return Me.estatusUUIDField
            End Get
            Set
                Me.estatusUUIDField = value
                Me.RaisePropertyChanged("estatusUUID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("uuid")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class wsCancelacionResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private acuseField As String
        
        Private codEstatusField As String
        
        Private foliosField() As folio
        
        Private mensajeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property acuse() As String
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
                Me.RaisePropertyChanged("acuse")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property codEstatus() As String
            Get
                Return Me.codEstatusField
            End Get
            Set
                Me.codEstatusField = value
                Me.RaisePropertyChanged("codEstatus")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property folios() As folio()
            Get
                Return Me.foliosField
            End Get
            Set
                Me.foliosField = value
                Me.RaisePropertyChanged("folios")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class accesos
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private passwordField As String
        
        Private usuarioField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
                Me.RaisePropertyChanged("usuario")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ObjectType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlNode
        
        Private idField As String
        
        Private mimeTypeField As String
        
        Private encodingField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set
                Me.mimeTypeField = value
                Me.RaisePropertyChanged("MimeType")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
                Me.RaisePropertyChanged("Encoding")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class RSAKeyValueType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private modulusField() As Byte
        
        Private exponentField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=0)>  _
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set
                Me.modulusField = value
                Me.RaisePropertyChanged("Modulus")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=1)>  _
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set
                Me.exponentField = value
                Me.RaisePropertyChanged("Exponent")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyValueType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private rSAKeyValueField() As RSAKeyValueType
        
        Private textField() As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", Order:=0)>  _
        Public Property RSAKeyValue() As RSAKeyValueType()
            Get
                Return Me.rSAKeyValueField
            End Get
            Set
                Me.rSAKeyValueField = value
                Me.RaisePropertyChanged("RSAKeyValue")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509IssuerSerialType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private x509IssuerNameField As String
        
        Private x509SerialNumberField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set
                Me.x509IssuerNameField = value
                Me.RaisePropertyChanged("X509IssuerName")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", Order:=1)>  _
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set
                Me.x509SerialNumberField = value
                Me.RaisePropertyChanged("X509SerialNumber")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509DataType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private x509IssuerSerialField As X509IssuerSerialType
        
        Private x509CertificateField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property X509IssuerSerial() As X509IssuerSerialType
            Get
                Return Me.x509IssuerSerialField
            End Get
            Set
                Me.x509IssuerSerialField = value
                Me.RaisePropertyChanged("X509IssuerSerial")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=1)>  _
        Public Property X509Certificate() As Byte()
            Get
                Return Me.x509CertificateField
            End Get
            Set
                Me.x509CertificateField = value
                Me.RaisePropertyChanged("X509Certificate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyInfoType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("KeyName", GetType(String), Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("KeyValue", GetType(KeyValueType), Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("X509Data", GetType(X509DataType), Order:=0)>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
                Me.RaisePropertyChanged("Items")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class DigestMethodType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class TransformType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xPathField() As String
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("XPath", Order:=0)>  _
        Public Property XPath() As String()
            Get
                Return Me.xPathField
            End Get
            Set
                Me.xPathField = value
                Me.RaisePropertyChanged("XPath")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ReferenceType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private transformsField() As TransformType
        
        Private digestMethodField As DigestMethodType
        
        Private digestValueField() As Byte
        
        Private idField As String
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
                Me.RaisePropertyChanged("Transforms")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = value
                Me.RaisePropertyChanged("DigestMethod")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=2)>  _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = value
                Me.RaisePropertyChanged("DigestValue")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
                Me.RaisePropertyChanged("URI")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("Type")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureMethodType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute(Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("HMACOutputLength", GetType(String), DataType:="integer", Order:=0)>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
                Me.RaisePropertyChanged("Items")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Cancelacion_2", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class Cancelacion_2Request
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public rfcEmisor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public fecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute("folios", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public folios() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public signatureType As FormasDigitales.SignatureType
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public accesos As FormasDigitales.accesos
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal signatureType As FormasDigitales.SignatureType, ByVal accesos As FormasDigitales.accesos)
            MyBase.New
            Me.rfcEmisor = rfcEmisor
            Me.fecha = fecha
            Me.folios = folios
            Me.signatureType = signatureType
            Me.accesos = accesos
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Cancelacion_2Response", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class Cancelacion_2Response
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As FormasDigitales.wsCancelacionResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As FormasDigitales.wsCancelacionResponse)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Cancelacion_1", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class Cancelacion_1Request
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public rfcEmisor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public fecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute("folios", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public folios() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)>  _
        Public publicKey() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)>  _
        Public privateKey() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=5),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public password As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=6),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public accesos As FormasDigitales.accesos
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal publicKey() As Byte, ByVal privateKey() As Byte, ByVal password As String, ByVal accesos As FormasDigitales.accesos)
            MyBase.New
            Me.rfcEmisor = rfcEmisor
            Me.fecha = fecha
            Me.folios = folios
            Me.publicKey = publicKey
            Me.privateKey = privateKey
            Me.password = password
            Me.accesos = accesos
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Cancelacion_1Response", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class Cancelacion_1Response
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As FormasDigitales.wsCancelacionResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As FormasDigitales.wsCancelacionResponse)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TimbrarZip", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class TimbrarZipRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public accesos As FormasDigitales.accesos
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public zip() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal accesos As FormasDigitales.accesos, ByVal zip() As Byte)
            MyBase.New
            Me.accesos = accesos
            Me.zip = zip
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TimbrarZipResponse", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class TimbrarZipResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public [return]() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public acuse As FormasDigitales.acuseRecepcionZip
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As Byte, ByVal acuse As FormasDigitales.acuseRecepcionZip)
            MyBase.New
            Me.[return] = [return]
            Me.acuse = acuse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TimbrarCFDI", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class TimbrarCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public accesos As FormasDigitales.accesos
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public comprobante As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal accesos As FormasDigitales.accesos, ByVal comprobante As String)
            MyBase.New
            Me.accesos = accesos
            Me.comprobante = comprobante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TimbrarCFDIResponse", WrapperNamespace:="http://wservicios/", IsWrapped:=true)>  _
    Partial Public Class TimbrarCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wservicios/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public acuseCFDI As FormasDigitales.acuseCFDI
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal acuseCFDI As FormasDigitales.acuseCFDI)
            MyBase.New
            Me.acuseCFDI = acuseCFDI
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSTimbradoCFDIChannel
        Inherits FormasDigitales.WSTimbradoCFDI, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSTimbradoCFDIClient
        Inherits System.ServiceModel.ClientBase(Of FormasDigitales.WSTimbradoCFDI)
        Implements FormasDigitales.WSTimbradoCFDI
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FormasDigitales_WSTimbradoCFDI_Cancelacion_2(ByVal request As FormasDigitales.Cancelacion_2Request) As FormasDigitales.Cancelacion_2Response Implements FormasDigitales.WSTimbradoCFDI.Cancelacion_2
            Return MyBase.Channel.Cancelacion_2(request)
        End Function
        
        Public Function Cancelacion_2(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal signatureType As FormasDigitales.SignatureType, ByVal accesos As FormasDigitales.accesos) As FormasDigitales.wsCancelacionResponse
            Dim inValue As FormasDigitales.Cancelacion_2Request = New FormasDigitales.Cancelacion_2Request()
            inValue.rfcEmisor = rfcEmisor
            inValue.fecha = fecha
            inValue.folios = folios
            inValue.signatureType = signatureType
            inValue.accesos = accesos
            Dim retVal As FormasDigitales.Cancelacion_2Response = CType(Me,FormasDigitales.WSTimbradoCFDI).Cancelacion_2(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FormasDigitales_WSTimbradoCFDI_Cancelacion_2Async(ByVal request As FormasDigitales.Cancelacion_2Request) As System.Threading.Tasks.Task(Of FormasDigitales.Cancelacion_2Response) Implements FormasDigitales.WSTimbradoCFDI.Cancelacion_2Async
            Return MyBase.Channel.Cancelacion_2Async(request)
        End Function
        
        Public Function Cancelacion_2Async(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal signatureType As FormasDigitales.SignatureType, ByVal accesos As FormasDigitales.accesos) As System.Threading.Tasks.Task(Of FormasDigitales.Cancelacion_2Response)
            Dim inValue As FormasDigitales.Cancelacion_2Request = New FormasDigitales.Cancelacion_2Request()
            inValue.rfcEmisor = rfcEmisor
            inValue.fecha = fecha
            inValue.folios = folios
            inValue.signatureType = signatureType
            inValue.accesos = accesos
            Return CType(Me,FormasDigitales.WSTimbradoCFDI).Cancelacion_2Async(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FormasDigitales_WSTimbradoCFDI_Cancelacion_1(ByVal request As FormasDigitales.Cancelacion_1Request) As FormasDigitales.Cancelacion_1Response Implements FormasDigitales.WSTimbradoCFDI.Cancelacion_1
            Return MyBase.Channel.Cancelacion_1(request)
        End Function
        
        Public Function Cancelacion_1(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal publicKey() As Byte, ByVal privateKey() As Byte, ByVal password As String, ByVal accesos As FormasDigitales.accesos) As FormasDigitales.wsCancelacionResponse
            Dim inValue As FormasDigitales.Cancelacion_1Request = New FormasDigitales.Cancelacion_1Request()
            inValue.rfcEmisor = rfcEmisor
            inValue.fecha = fecha
            inValue.folios = folios
            inValue.publicKey = publicKey
            inValue.privateKey = privateKey
            inValue.password = password
            inValue.accesos = accesos
            Dim retVal As FormasDigitales.Cancelacion_1Response = CType(Me,FormasDigitales.WSTimbradoCFDI).Cancelacion_1(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FormasDigitales_WSTimbradoCFDI_Cancelacion_1Async(ByVal request As FormasDigitales.Cancelacion_1Request) As System.Threading.Tasks.Task(Of FormasDigitales.Cancelacion_1Response) Implements FormasDigitales.WSTimbradoCFDI.Cancelacion_1Async
            Return MyBase.Channel.Cancelacion_1Async(request)
        End Function
        
        Public Function Cancelacion_1Async(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal publicKey() As Byte, ByVal privateKey() As Byte, ByVal password As String, ByVal accesos As FormasDigitales.accesos) As System.Threading.Tasks.Task(Of FormasDigitales.Cancelacion_1Response)
            Dim inValue As FormasDigitales.Cancelacion_1Request = New FormasDigitales.Cancelacion_1Request()
            inValue.rfcEmisor = rfcEmisor
            inValue.fecha = fecha
            inValue.folios = folios
            inValue.publicKey = publicKey
            inValue.privateKey = privateKey
            inValue.password = password
            inValue.accesos = accesos
            Return CType(Me,FormasDigitales.WSTimbradoCFDI).Cancelacion_1Async(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FormasDigitales_WSTimbradoCFDI_TimbrarZip(ByVal request As FormasDigitales.TimbrarZipRequest) As FormasDigitales.TimbrarZipResponse Implements FormasDigitales.WSTimbradoCFDI.TimbrarZip
            Return MyBase.Channel.TimbrarZip(request)
        End Function
        
        Public Function TimbrarZip(ByVal accesos As FormasDigitales.accesos, ByVal zip() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef acuse As FormasDigitales.acuseRecepcionZip) As Byte()
            Dim inValue As FormasDigitales.TimbrarZipRequest = New FormasDigitales.TimbrarZipRequest()
            inValue.accesos = accesos
            inValue.zip = zip
            Dim retVal As FormasDigitales.TimbrarZipResponse = CType(Me,FormasDigitales.WSTimbradoCFDI).TimbrarZip(inValue)
            acuse = retVal.acuse
            Return retVal.[return]
        End Function
        
        Public Function TimbrarZipAsync(ByVal request As FormasDigitales.TimbrarZipRequest) As System.Threading.Tasks.Task(Of FormasDigitales.TimbrarZipResponse) Implements FormasDigitales.WSTimbradoCFDI.TimbrarZipAsync
            Return MyBase.Channel.TimbrarZipAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FormasDigitales_WSTimbradoCFDI_TimbrarCFDI(ByVal request As FormasDigitales.TimbrarCFDIRequest) As FormasDigitales.TimbrarCFDIResponse Implements FormasDigitales.WSTimbradoCFDI.TimbrarCFDI
            Return MyBase.Channel.TimbrarCFDI(request)
        End Function
        
        Public Function TimbrarCFDI(ByVal accesos As FormasDigitales.accesos, ByVal comprobante As String) As FormasDigitales.acuseCFDI
            Dim inValue As FormasDigitales.TimbrarCFDIRequest = New FormasDigitales.TimbrarCFDIRequest()
            inValue.accesos = accesos
            inValue.comprobante = comprobante
            Dim retVal As FormasDigitales.TimbrarCFDIResponse = CType(Me,FormasDigitales.WSTimbradoCFDI).TimbrarCFDI(inValue)
            Return retVal.acuseCFDI
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FormasDigitales_WSTimbradoCFDI_TimbrarCFDIAsync(ByVal request As FormasDigitales.TimbrarCFDIRequest) As System.Threading.Tasks.Task(Of FormasDigitales.TimbrarCFDIResponse) Implements FormasDigitales.WSTimbradoCFDI.TimbrarCFDIAsync
            Return MyBase.Channel.TimbrarCFDIAsync(request)
        End Function
        
        Public Function TimbrarCFDIAsync(ByVal accesos As FormasDigitales.accesos, ByVal comprobante As String) As System.Threading.Tasks.Task(Of FormasDigitales.TimbrarCFDIResponse)
            Dim inValue As FormasDigitales.TimbrarCFDIRequest = New FormasDigitales.TimbrarCFDIRequest()
            inValue.accesos = accesos
            inValue.comprobante = comprobante
            Return CType(Me,FormasDigitales.WSTimbradoCFDI).TimbrarCFDIAsync(inValue)
        End Function
    End Class
End Namespace
