//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Equipo
    {
        public Equipo()
        {
            this.Tarea = new HashSet<Tarea>();
        }

        [Required(ErrorMessage = "Campo obligatorio")]
        public string idEquipo { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string correo { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string contrasena { get; set; }
        public Nullable<int> inversion_horas_dia { get; set; }
        public Nullable<decimal> costo_hr { get; set; }
        public string perfil { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
