//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Esfuerzo
    {
        public int idEsfuerzo { get; set; }
        public int idTarea { get; set; }

        public System.DateTime fecha_actual { get; set; }
        public double consumo_hrs { get; set; }
        public Nullable<double> restantes { get; set; }
        public Nullable<double> hrs_reales { get; set; }
        public Nullable<decimal> costo_hrs { get; set; }
        public string comentarios { get; set; }
    
        public virtual Tarea Tarea { get; set; }
    }
}
