//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riesgos
    {
        public int idRiesgos { get; set; }
        public string idProyecto { get; set; }
        public int idTarea { get; set; }
        public int idEstado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string descripcion { get; set; }
        public string responsable { get; set; }
        public Nullable<int> criticidad { get; set; }
        public Nullable<int> probabilidad { get; set; }
        public Nullable<int> impacto { get; set; }
        public string mitigacion { get; set; }
        public Nullable<System.DateTime> fecha_seguimiento { get; set; }
    
        public virtual Estados_tareas Estados_tareas { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
