//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigParametro
    {
        public string Parametro { get; set; }
        public string Identificador { get; set; }
        public string Valor { get; set; }
        public Nullable<short> Nivel { get; set; }
        public short TipoAplicacion { get; set; }
    }
}
