//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalSerial
    {
        public string DispositivoID { get; set; }
        public string Nombre_Dispositivo { get; set; }
        public Nullable<int> TipoLicencia { get; set; }
        public string LlaveHost { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> IntentosRestantes { get; set; }
        public Nullable<System.DateTime> FechaActivacion { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioID { get; set; }
    }
}
