//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public string TerminalClave { get; set; }
        public short TipoFase { get; set; }
        public string Descripcion { get; set; }
        public string NumeroSerie { get; set; }
        public string Comentario { get; set; }
        public bool GPS { get; set; }
        public string AlmacenID { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioID { get; set; }
    }
}
