SET NOCOUNT ON
IF EXISTS (SELECT * FROM sys.objects WHERE TYPE='P' AND NAME='stpr_Cobranza_16')
	DROP PROCEDURE [dbo].[stpr_Cobranza_16]
SET NOCOUNT OFF
/*go*/go

CREATE PROCEDURE [dbo].[stpr_Cobranza_16]
@FILTROCEDI AS VARCHAR(20),
@FILTRORUTAS AS VARCHAR(MAX) = NULL,
@FILTROFECHAINI AS VARCHAR(10),
@FILTROFECHAFIN AS VARCHAR(10)
AS
	SET NOCOUNT ON
	DECLARE
		@CEDI AS VARCHAR(20),
		@RUTAS AS VARCHAR(MAX) = NULL,
		@FECHAINI AS DATETIME,
		@FECHAFIN AS DATETIME

	IF NOT COALESCE(@FILTROCEDI,'') = ''
		SET @CEDI = @FILTROCEDI

	IF NOT COALESCE(@FILTRORUTAS,'') = ''
		SET @RUTAS = @FILTRORUTAS

	IF NOT COALESCE(@FILTROFECHAINI,'') = ''
		SET @FECHAINI = @FILTROFECHAINI

	IF NOT COALESCE(@FILTROFECHAFIN,'') = ''
		SET @FECHAFIN = @FILTROFECHAFIN

	SELECT
		ABN.FechaCreacion AS [Fecha|FORMAT%d], RUT.RUTClave, RUT.Descripcion, CLI.Clave, CLI.RazonSocial, TRP.Folio, TRP.Total,
		(ISNULL((
			SELECT SUM(importe) FROM AbnTrp WHERE TransProdID = ABT.TransProdId AND ABT.FechaHora < FechaHora GROUP BY TransProdID), 0)) + TRP.Saldo AS Saldo,
		VAD1.Descripcion AS TipoPago, ISNULL(ABD.Referencia, '') AS Referencia , ABT.Importe AS [Importe|FORMAT&$|SUMMARY]
	FROM Abono ABN (NOLOCK)
		INNER JOIN AbnTrp ABT (NOLOCK) ON ABN.ABNId = ABT.ABNId
		INNER JOIN Visita VIS (NOLOCK) ON ABN.VisitaClave = VIS.VisitaClave AND ABN.DiaClave = VIS.DiaClave
		INNER JOIN Dia D (NOLOCK) ON VIS.DiaClave = D.DiaClave
		INNER JOIN Vendedor VEN (NOLOCK) ON VIS.VendedorID = VEN.VendedorID
		INNER JOIN VenRut VRUT (NOLOCK) ON VEN.VendedorID = VRUT.VendedorID AND VRUT.TipoEstado = 1
		INNER JOIN Ruta RUT (NOLOCK) ON VRUT.RUTClave = RUT.RUTClave
		INNER JOIN Usuario USU (NOLOCK) ON VEN.USUId = USU.USUId
		RIGHT JOIN ABNDetalle ABD (NOLOCK) ON ABN.ABNId = ABD.ABNId
		LEFT JOIN TransProd TRP (NOLOCK) ON ABT.TransProdID = TRP.TransProdID
		LEFT JOIN Cliente CLI (NOLOCK) ON TRP.ClienteClave = CLI.ClienteClave
		LEFT JOIN VavDescripcion VAD1 (NOLOCK) ON VAD1.VARCodigo = 'PAGO' AND VAD1.VAVClave = (SELECT TOP 1 ABD.TipoPago FROM ABNDetalle WHERE ABNId = ABN.ABNId)
			AND VAD1.VADTipoLenguaje = dbo.FNObtenerLenguaje() 
	WHERE ((RUT.RUTClave IN (SELECT Datos FROM [dbo].[FNSplit](@RUTAS, ','))) OR @RUTAS IS NULL) 
		AND CONVERT(DATETIME,CONVERT(VARCHAR(20),ABN.FechaCreacion,112)) BETWEEN @FILTROFECHAINI AND @FILTROFECHAFIN
	ORDER BY CLI.Clave

	SET NOCOUNT OFF
/*go*/go