'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace mx.facturacfdi.dev
    
    'CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://www.w3.org/ns/ws-policy'.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSTimbradoCFDIPortBinding", [Namespace]:="http://wservicios/")>  _
    Partial Public Class WSTimbradoCFDIService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Cancelacion_2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Cancelacion_1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbrarZipOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbrarCFDIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Selling.MySettings.Default.Selling_mx_facturacfdi_dev_WSTimbradoCFDIService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Cancelacion_2Completed As Cancelacion_2CompletedEventHandler
        
        '''<remarks/>
        Public Event Cancelacion_1Completed As Cancelacion_1CompletedEventHandler
        
        '''<remarks/>
        Public Event TimbrarZipCompleted As TimbrarZipCompletedEventHandler
        
        '''<remarks/>
        Public Event TimbrarCFDICompleted As TimbrarCFDICompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://wservicios/", ResponseNamespace:="http://wservicios/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Cancelacion_2(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal rfcEmisor As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal fecha As String, <System.Xml.Serialization.XmlElementAttribute("folios", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal folios() As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal signatureType As SignatureType, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal accesos As accesos) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsCancelacionResponse
            Dim results() As Object = Me.Invoke("Cancelacion_2", New Object() {rfcEmisor, fecha, folios, signatureType, accesos})
            Return CType(results(0),wsCancelacionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Cancelacion_2Async(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal signatureType As SignatureType, ByVal accesos As accesos)
            Me.Cancelacion_2Async(rfcEmisor, fecha, folios, signatureType, accesos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Cancelacion_2Async(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal signatureType As SignatureType, ByVal accesos As accesos, ByVal userState As Object)
            If (Me.Cancelacion_2OperationCompleted Is Nothing) Then
                Me.Cancelacion_2OperationCompleted = AddressOf Me.OnCancelacion_2OperationCompleted
            End If
            Me.InvokeAsync("Cancelacion_2", New Object() {rfcEmisor, fecha, folios, signatureType, accesos}, Me.Cancelacion_2OperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelacion_2OperationCompleted(ByVal arg As Object)
            If (Not (Me.Cancelacion_2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Cancelacion_2Completed(Me, New Cancelacion_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://wservicios/", ResponseNamespace:="http://wservicios/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Cancelacion_1(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal rfcEmisor As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal fecha As String, <System.Xml.Serialization.XmlElementAttribute("folios", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal folios() As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal publicKey() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal privateKey() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal accesos As accesos) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsCancelacionResponse
            Dim results() As Object = Me.Invoke("Cancelacion_1", New Object() {rfcEmisor, fecha, folios, publicKey, privateKey, password, accesos})
            Return CType(results(0),wsCancelacionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Cancelacion_1Async(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal publicKey() As Byte, ByVal privateKey() As Byte, ByVal password As String, ByVal accesos As accesos)
            Me.Cancelacion_1Async(rfcEmisor, fecha, folios, publicKey, privateKey, password, accesos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Cancelacion_1Async(ByVal rfcEmisor As String, ByVal fecha As String, ByVal folios() As String, ByVal publicKey() As Byte, ByVal privateKey() As Byte, ByVal password As String, ByVal accesos As accesos, ByVal userState As Object)
            If (Me.Cancelacion_1OperationCompleted Is Nothing) Then
                Me.Cancelacion_1OperationCompleted = AddressOf Me.OnCancelacion_1OperationCompleted
            End If
            Me.InvokeAsync("Cancelacion_1", New Object() {rfcEmisor, fecha, folios, publicKey, privateKey, password, accesos}, Me.Cancelacion_1OperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelacion_1OperationCompleted(ByVal arg As Object)
            If (Not (Me.Cancelacion_1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Cancelacion_1Completed(Me, New Cancelacion_1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://wservicios/", ResponseNamespace:="http://wservicios/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbrarZip(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal accesos As accesos, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")> ByVal zip() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByRef acuse As acuseRecepcionZip) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("TimbrarZip", New Object() {accesos, zip})
            acuse = CType(results(1),acuseRecepcionZip)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbrarZipAsync(ByVal accesos As accesos, ByVal zip() As Byte)
            Me.TimbrarZipAsync(accesos, zip, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbrarZipAsync(ByVal accesos As accesos, ByVal zip() As Byte, ByVal userState As Object)
            If (Me.TimbrarZipOperationCompleted Is Nothing) Then
                Me.TimbrarZipOperationCompleted = AddressOf Me.OnTimbrarZipOperationCompleted
            End If
            Me.InvokeAsync("TimbrarZip", New Object() {accesos, zip}, Me.TimbrarZipOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbrarZipOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbrarZipCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbrarZipCompleted(Me, New TimbrarZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://wservicios/", ResponseNamespace:="http://wservicios/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbrarCFDI(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal accesos As accesos, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal comprobante As String) As <System.Xml.Serialization.XmlElementAttribute("acuseCFDI", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> acuseCFDI
            Dim results() As Object = Me.Invoke("TimbrarCFDI", New Object() {accesos, comprobante})
            Return CType(results(0),acuseCFDI)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbrarCFDIAsync(ByVal accesos As accesos, ByVal comprobante As String)
            Me.TimbrarCFDIAsync(accesos, comprobante, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbrarCFDIAsync(ByVal accesos As accesos, ByVal comprobante As String, ByVal userState As Object)
            If (Me.TimbrarCFDIOperationCompleted Is Nothing) Then
                Me.TimbrarCFDIOperationCompleted = AddressOf Me.OnTimbrarCFDIOperationCompleted
            End If
            Me.InvokeAsync("TimbrarCFDI", New Object() {accesos, comprobante}, Me.TimbrarCFDIOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbrarCFDIOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbrarCFDICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbrarCFDICompleted(Me, New TimbrarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureType
        
        Private signedInfoField As SignedInfoType
        
        Private signatureValueField() As Byte
        
        Private keyInfoField As KeyInfoType
        
        Private objectField() As ObjectType
        
        Private idField As String
        
        '''<comentarios/>
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property SignatureValue() As Byte()
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Object")>  _
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set
                Me.objectField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignedInfoType
        
        Private canonicalizationMethodField As CanonicalizationMethodType
        
        Private signatureMethodField As SignatureMethodType
        
        Private referenceField As ReferenceType
        
        Private idField As String
        
        '''<comentarios/>
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Reference() As ReferenceType
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class CanonicalizationMethodType
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class acuseCFDI
        
        Private codigoErrorField As Integer
        
        Private codigoErrorFieldSpecified As Boolean
        
        Private errorField As String
        
        Private xmlTimbradoField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoErrorSpecified() As Boolean
            Get
                Return Me.codigoErrorFieldSpecified
            End Get
            Set
                Me.codigoErrorFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property xmlTimbrado() As String
            Get
                Return Me.xmlTimbradoField
            End Get
            Set
                Me.xmlTimbradoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class acuseZip
        
        Private errorField As String
        
        Private nombrexmlField As String
        
        Private uuidField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombrexml() As String
            Get
                Return Me.nombrexmlField
            End Get
            Set
                Me.nombrexmlField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class acuseRecepcionZip
        
        Private codigoErrorField As Integer
        
        Private codigoErrorFieldSpecified As Boolean
        
        Private errorField As String
        
        Private listaCFDIsField() As acuseZip
        
        Private nombrezipField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoErrorSpecified() As Boolean
            Get
                Return Me.codigoErrorFieldSpecified
            End Get
            Set
                Me.codigoErrorFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("listaCFDIs", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property listaCFDIs() As acuseZip()
            Get
                Return Me.listaCFDIsField
            End Get
            Set
                Me.listaCFDIsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombrezip() As String
            Get
                Return Me.nombrezipField
            End Get
            Set
                Me.nombrezipField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class folio
        
        Private estatusUUIDField As String
        
        Private mensajeField As String
        
        Private uuidField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estatusUUID() As String
            Get
                Return Me.estatusUUIDField
            End Get
            Set
                Me.estatusUUIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class wsCancelacionResponse
        
        Private acuseField As String
        
        Private codEstatusField As String
        
        Private foliosField() As folio
        
        Private mensajeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property acuse() As String
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codEstatus() As String
            Get
                Return Me.codEstatusField
            End Get
            Set
                Me.codEstatusField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property folios() As folio()
            Get
                Return Me.foliosField
            End Get
            Set
                Me.foliosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wservicios/")>  _
    Partial Public Class accesos
        
        Private passwordField As String
        
        Private usuarioField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ObjectType
        
        Private anyField() As System.Xml.XmlNode
        
        Private idField As String
        
        Private mimeTypeField As String
        
        Private encodingField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set
                Me.mimeTypeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class RSAKeyValueType
        
        Private modulusField() As Byte
        
        Private exponentField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set
                Me.modulusField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set
                Me.exponentField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyValueType
        
        Private rSAKeyValueField() As RSAKeyValueType
        
        Private textField() As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("RSAKeyValue")>  _
        Public Property RSAKeyValue() As RSAKeyValueType()
            Get
                Return Me.rSAKeyValueField
            End Get
            Set
                Me.rSAKeyValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509IssuerSerialType
        
        Private x509IssuerNameField As String
        
        Private x509SerialNumberField As String
        
        '''<comentarios/>
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set
                Me.x509IssuerNameField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set
                Me.x509SerialNumberField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509DataType
        
        Private x509IssuerSerialField As X509IssuerSerialType
        
        Private x509CertificateField() As Byte
        
        '''<comentarios/>
        Public Property X509IssuerSerial() As X509IssuerSerialType
            Get
                Return Me.x509IssuerSerialField
            End Get
            Set
                Me.x509IssuerSerialField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property X509Certificate() As Byte()
            Get
                Return Me.x509CertificateField
            End Get
            Set
                Me.x509CertificateField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyInfoType
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("KeyName", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("KeyValue", GetType(KeyValueType)),  _
         System.Xml.Serialization.XmlElementAttribute("X509Data", GetType(X509DataType))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class DigestMethodType
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class TransformType
        
        Private xPathField() As String
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("XPath")>  _
        Public Property XPath() As String()
            Get
                Return Me.xPathField
            End Get
            Set
                Me.xPathField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ReferenceType
        
        Private transformsField() As TransformType
        
        Private digestMethodField As DigestMethodType
        
        Private digestValueField() As Byte
        
        Private idField As String
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureMethodType
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("HMACOutputLength", GetType(String), DataType:="integer")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub Cancelacion_2CompletedEventHandler(ByVal sender As Object, ByVal e As Cancelacion_2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Cancelacion_2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsCancelacionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsCancelacionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub Cancelacion_1CompletedEventHandler(ByVal sender As Object, ByVal e As Cancelacion_1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Cancelacion_1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsCancelacionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsCancelacionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub TimbrarZipCompletedEventHandler(ByVal sender As Object, ByVal e As TimbrarZipCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbrarZipCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property acuse() As acuseRecepcionZip
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),acuseRecepcionZip)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub TimbrarCFDICompletedEventHandler(ByVal sender As Object, ByVal e As TimbrarCFDICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbrarCFDICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As acuseCFDI
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),acuseCFDI)
            End Get
        End Property
    End Class
End Namespace
