
use RouteCPC 

insert into GReportesNaturaleza values ( 1, 'NOTAS DE CARGO', 'N', 1)
insert into GReportesNaturaleza values ( 2, 'NOTAS DE CRÉDITO', 'N', 2)
insert into GReportesNaturaleza values ( 3, 'NR PARA SALDAR FACTURAS', 'N', 3)
insert into GReportesNaturaleza values ( 4, 'PAGO DE FACTURAS', 'N', 4)
insert into GReportesNaturaleza values ( 5, 'NR ACUERDO', 'N', 11)
insert into GReportesNaturaleza values ( 6, 'ANTIGUEDAD DE SALDOS', 'S', 12)
insert into GReportesNaturaleza values ( 7, 'ANTIGUEDAD DE SALDOS DETALLADA', 'S', 13)
insert into GReportesNaturaleza values ( 8, 'BALANZA DE CLIENTES', 'S', 14)
insert into GReportesNaturaleza values ( 9, 'VENTAS POR CLIENTE', 'S', 16)
insert into GReportesNaturaleza values ( 10, 'DEPOSITOS HSBC', 'N', 5)
insert into GReportesNaturaleza values ( 11, 'DEPOSITOS BAJIO', 'N', 6)
insert into GReportesNaturaleza values ( 12, 'DEPOSITOS BANCOMER', 'N', 7)
insert into GReportesNaturaleza values ( 13, 'DEPOSITOS BANAMEX', 'N', 8)
insert into GReportesNaturaleza values ( 14, 'DEPOSITOS HSBC', 'N', 9)
insert into GReportesNaturaleza values ( 15, 'AVISOS DE CREDITO', 'N', 10)
insert into GReportesNaturaleza values ( 16, 'CONCILIACION BANCARIA', 'S', 17)
insert into GReportesNaturaleza values ( 17, 'DEPÓSITOS POR CLIENTE Y BANCO', 'S', 18)
insert into GReportesNaturaleza values ( 18, 'BALANZA DE CLIENTES DETALLADA', 'S', 15)
insert into GReportesNaturaleza values ( 19, 'DETALLADO DE ACUERDOS', 'S', 19)
insert into GReportesNaturaleza values ( 20, 'Cobranza Terminales', 'S', 20)
insert into GReportesNaturaleza values ( 100, 'P. DIARIO DE VENTAS', 'S', 100)
insert into GReportesNaturaleza values ( 101, 'P. LIBRO DE VENTAS', 'S', 101)
insert into GReportesNaturaleza values ( 102, 'P. RESUMEN DE MOVIMIENTOS', 'S', 102)
insert into GReportesNaturaleza values ( 103, 'P. IVA POR PAGAR COBRADO', 'S', 103)
insert into GReportesNaturaleza values ( 104, 'P. IETU', 'S', 104)
insert into GReportesNaturaleza values ( 105, 'P. MERMAS Y OBSEQUIOS', 'S', 105)

insert into GReportesNivel values ('1', '1', 'PR - Diferencia de Precio', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'N', '', '11', '0', '18')
insert into GReportesNivel values ('2', '1', 'AC - Apoyos Comerciales', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('2', '2', 'AP - Alta de Productos', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('2', '3', 'AT - Alta de Tiendas', '30', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '31', '0', '18')
insert into GReportesNivel values ('2', '4', 'CD - Cheques devueltos', '40', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '41', '0', '18')
insert into GReportesNivel values ('2', '5', 'CI - Cuentas Incobrables', '50', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '51', '0', '18')
insert into GReportesNivel values ('2', '6', 'DCTO - Descuentos', '60', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '61', '0', '18')
insert into GReportesNivel values ('2', '7', 'DL - Descuentos Logisticos', '70', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '71', '0', '18')
insert into GReportesNivel values ('2', '8', 'DP - Diferencia de Precios', '80', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '81', '0', '18')
insert into GReportesNivel values ('2', '9', 'MO - Metas y Objetivos', '90', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '91', '0', '18')
insert into GReportesNivel values ('2', '10', 'NG - Negociacion', '100', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '101', '0', '18')
insert into GReportesNivel values ('2', '11', 'OB - Obsequios', '110', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '111', '0', '18')
insert into GReportesNivel values ('2', '12', 'OX - Saldar Oxxo', '120', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '121', '0', '18')
insert into GReportesNivel values ('2', '13', 'PB - Publicidad', '130', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '131', '0', '18')
insert into GReportesNivel values ('2', '14', 'PD - Por Devolucion', '140', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '141', '0', '18')
insert into GReportesNivel values ('2', '15', 'PE - Promociones Especiales', '150', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '151', '0', '18')
insert into GReportesNivel values ('2', '16', 'VR - Varios', '160', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '161', '0', '18')
insert into GReportesNivel values ('3', '1', 'AJ - Ajuste para Saldar', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('4', '1', 'CH - Cheque', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('4', '2', 'EF - Efectivo', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('4', '3', 'TB - Transferencia', '30', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '31', '0', '18')
insert into GReportesNivel values ('5', '1', 'PU - Publicidad', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('6', '1', 'Por Cliente', '10', '0', '1', 'Clientes.IdCliente', 'S', 'S', 'S', '', '11', '0', '10')
insert into GReportesNivel values ('6', '2', 'Por Sucursal de Cliente', '20', '0', '1', 'Clientes.IdCliente', 'S', 'S', 'S', '', '21', '0', '10')
insert into GReportesNivel values ('6', '3', 'Por Marca', '30', '0', '1', 'FN_VencimientoAlaFechaS.IdMarca', 'S', 'S', 'S', '', '31', '0', '11')
insert into GReportesNivel values ('7', '1', 'Por Cliente', '10', '0', '1', 'Clientes.IdCliente', 'S', 'S', 'S', '', '11', '0', '9')
insert into GReportesNivel values ('7', '2', 'Por Sucursal de Cliente', '20', '0', '1', 'Clientes.IdCliente', 'S', 'S', 'S', '', '21', '0', '9')
insert into GReportesNivel values ('7', '3', 'Por Marca', '30', '0', '1', 'FN_VencimientoAlaFechaS.IdMarca', 'S', 'S', 'S', '', '31', '0', '10')
insert into GReportesNivel values ('8', '1', 'Por Cliente', '10', '0', '1', 'Clientes.IdCliente', 'S', 'S', 'S', '', '11', '0', '8')
insert into GReportesNivel values ('8', '2', 'Por Sucursal de Cliente', '20', '0', '1', 'Clientes.IdCliente', 'S', 'S', 'S', '', '21', '0', '8')
insert into GReportesNivel values ('8', '3', 'Por Marca', '30', '0', '1', 'FN_SaldosPorFechaS.IdMarca', 'S', 'S', 'S', '', '31', '0', '9')
insert into GReportesNivel values ('9', '1', 'Por Cliente', '10', '0', '1', 'Clientes.IdCliente', 'S', 'S', 'S', '', '11', '0', '11')
insert into GReportesNivel values ('10', '1', 'CH - Cheque', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('10', '2', 'EF - Efectivo', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('10', '3', 'TB - Transferencia', '30', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '31', '0', '18')
insert into GReportesNivel values ('11', '1', 'CH - Cheque', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('11', '2', 'EF - Efectivo', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('11', '3', 'TB - Transferencia', '30', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '31', '0', '18')
insert into GReportesNivel values ('12', '1', 'CH - Cheque', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('12', '2', 'EF - Efectivo', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('12', '3', 'TB - Transferencia', '30', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '31', '0', '18')
insert into GReportesNivel values ('13', '1', 'CH - Cheque', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('13', '2', 'EF - Efectivo', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('13', '3', 'TB - Transferencia', '30', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '31', '0', '18')
insert into GReportesNivel values ('14', '1', 'CH - Cheque', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('14', '2', 'EF - Efectivo', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('14', '3', 'TB - Transferencia', '30', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '31', '0', '18')
insert into GReportesNivel values ('15', '1', 'AN - Aviso CR Nomina', '10', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '11', '0', '18')
insert into GReportesNivel values ('15', '2', 'AV - Aviso CR Varios', '20', '0', '2', 'MovimientosFacturas.IdMovimiento', 'S', 'S', 'S', '', '21', '0', '18')
insert into GReportesNivel values ('16', '1', 'Por Documento', '10', '0', '2', 'Movimientos.IdDocumento', 'S', 'S', 'S', '', '11', '0', '6')
insert into GReportesNivel values ('17', '1', 'Por Cedis', '10', '0', '2', 'FN_ClientesBancos.IdCedis', 'S', 'S', 'S', '', '11', '0', '8')
insert into GReportesNivel values ('18', '1', 'Por Cliente', '10', '0', '2', 'Clientes.IdCliente', 'S', 'S', 'S', '', '11', '0', '13')
insert into GReportesNivel values ('18', '2', 'Por Sucursal de Cliente', '20', '0', '2', 'Clientes.IdCliente', 'S', 'S', 'S', '', '21', '0', '13')
insert into GReportesNivel values ('18', '3', 'Por Marca', '30', '0', '1', 'FN_BalanzaDetalladaS.IdMarca', 'S', 'S', 'S', '', '31', '0', '14')
insert into GReportesNivel values ('19', '1', 'Por Folio', '10', '0', '3', 'PromocionesAplicadas.IdAplicacion', 'S', 'S', 'S', '', '11', '0', '15')
insert into GReportesNivel values ('20', '1', 'Por Fecha', '10', '0', '0', 'Fecha', 'S', 'S', 'S', 'Fecha', '11', '0', '6')
insert into GReportesNivel values ('100', '1', 'Por Cedis y por Producto', '10', '0', '2', 'CED.IdCedis', 'S', 'S', 'S', '', '11', '0', '8')
insert into GReportesNivel values ('101', '1', 'Por Cedis y por Producto', '10', '0', '2', 'CED.IdCedis', 'S', 'S', 'S', '', '11', '0', '13')
insert into GReportesNivel values ('102', '1', 'Por Cedis', '10', '0', '2', 'IdCedis', 'S', 'S', 'S', '', '11', '0', '5')
insert into GReportesNivel values ('103', '1', 'Por Cedis', '10', '0', '2', 'MovimientosFacturas.IdCedis', 'S', 'S', 'S', '', '11', '0', '15')
insert into GReportesNivel values ('104', '1', 'Por Cedis', '10', '0', '2', 'MovimientosFacturas.IdCedis', 'S', 'S', 'S', '', '11', '0', '12')
insert into GReportesNivel values ('105', '1', 'Por Cedis', '10', '0', '2', 'FN_MermasObsequios.IdCedis', 'S', 'S', 'S', '', '11', '0', '8')

