update Rejas set Surtido = 132, Devolucion = 158 where IdCedis = 3 and IdSurtido = 612
update Rejas set Surtido = 91, Devolucion = 88 where IdCedis = 3 and IdSurtido = 649
update Rejas set Surtido = 83, Devolucion = 90 where IdCedis = 3 and IdSurtido = 687
update Rejas set Surtido = 97, Devolucion = 110 where IdCedis = 3 and IdSurtido = 728
update Rejas set Surtido = 80, Devolucion = 121 where IdCedis = 3 and IdSurtido = 614
update Rejas set Surtido = 114, Devolucion = 126 where IdCedis = 3 and IdSurtido = 651
update Rejas set Surtido = 119, Devolucion = 114 where IdCedis = 3 and IdSurtido = 689
update Rejas set Surtido = 77, Devolucion = 85 where IdCedis = 3 and IdSurtido = 730
update Rejas set Surtido = 15, Devolucion = 15 where IdCedis = 3 and IdSurtido = 751
update Rejas set Surtido = 87, Devolucion = 90 where IdCedis = 3 and IdSurtido = 631
update Rejas set Surtido = 83, Devolucion = 74 where IdCedis = 3 and IdSurtido = 663
update Rejas set Surtido = 85, Devolucion = 102 where IdCedis = 3 and IdSurtido = 698
update Rejas set Surtido = 103, Devolucion = 108 where IdCedis = 3 and IdSurtido = 737
update Rejas set Surtido = 66, Devolucion = 71 where IdCedis = 3 and IdSurtido = 610
update Rejas set Surtido = 64, Devolucion = 73 where IdCedis = 3 and IdSurtido = 647
update Rejas set Surtido = 43, Devolucion = 43 where IdCedis = 3 and IdSurtido = 685
update Rejas set Surtido = 50, Devolucion = 56 where IdCedis = 3 and IdSurtido = 726
update Rejas set Surtido = 146, Devolucion = 0 where IdCedis = 3 and IdSurtido = 633
update Rejas set Surtido = 103, Devolucion = 0 where IdCedis = 3 and IdSurtido = 700
update Rejas set Surtido = 96, Devolucion = 112 where IdCedis = 3 and IdSurtido = 621
update Rejas set Surtido = 66, Devolucion = 0 where IdCedis = 3 and IdSurtido = 641
update Rejas set Surtido = 52, Devolucion = 94 where IdCedis = 3 and IdSurtido = 676
update Rejas set Surtido = 51, Devolucion = 99 where IdCedis = 3 and IdSurtido = 714
update Rejas set Surtido = 137, Devolucion = 134 where IdCedis = 3 and IdSurtido = 615
update Rejas set Surtido = 45, Devolucion = 55 where IdCedis = 3 and IdSurtido = 652
update Rejas set Surtido = 167, Devolucion = 13 where IdCedis = 3 and IdSurtido = 675
update Rejas set Surtido = 151, Devolucion = 160 where IdCedis = 3 and IdSurtido = 716
update Rejas set Surtido = 94, Devolucion = 157 where IdCedis = 3 and IdSurtido = 758
update Rejas set Surtido = 95, Devolucion = 130 where IdCedis = 3 and IdSurtido = 613
update Rejas set Surtido = 77, Devolucion = 88 where IdCedis = 3 and IdSurtido = 650
update Rejas set Surtido = 85, Devolucion = 71 where IdCedis = 3 and IdSurtido = 688
update Rejas set Surtido = 52, Devolucion = 58 where IdCedis = 3 and IdSurtido = 729
update Rejas set Surtido = 78, Devolucion = 78 where IdCedis = 3 and IdSurtido = 622
update Rejas set Surtido = 77, Devolucion = 0 where IdCedis = 3 and IdSurtido = 638
update Rejas set Surtido = 74, Devolucion = 112 where IdCedis = 3 and IdSurtido = 674
update Rejas set Surtido = 41, Devolucion = 97 where IdCedis = 3 and IdSurtido = 715
update Rejas set Surtido = 118, Devolucion = 158 where IdCedis = 3 and IdSurtido = 627
update Rejas set Surtido = 98, Devolucion = 99 where IdCedis = 3 and IdSurtido = 660
update Rejas set Surtido = 47, Devolucion = 53 where IdCedis = 3 and IdSurtido = 695
update Rejas set Surtido = 21, Devolucion = 21 where IdCedis = 3 and IdSurtido = 710
update Rejas set Surtido = 154, Devolucion = 164 where IdCedis = 3 and IdSurtido = 740
update Rejas set Surtido = 66, Devolucion = 64 where IdCedis = 3 and IdSurtido = 620
update Rejas set Surtido = 72, Devolucion = 74 where IdCedis = 3 and IdSurtido = 656
update Rejas set Surtido = 38, Devolucion = 0 where IdCedis = 3 and IdSurtido = 677
update Rejas set Surtido = 35, Devolucion = 71 where IdCedis = 3 and IdSurtido = 719
update Rejas set Surtido = 44, Devolucion = 36 where IdCedis = 3 and IdSurtido = 754
update Rejas set Surtido = 90, Devolucion = 87 where IdCedis = 3 and IdSurtido = 606
update Rejas set Surtido = 44, Devolucion = 55 where IdCedis = 3 and IdSurtido = 643
update Rejas set Surtido = 44, Devolucion = 46 where IdCedis = 3 and IdSurtido = 681
update Rejas set Surtido = 60, Devolucion = 60 where IdCedis = 3 and IdSurtido = 722
update Rejas set Surtido = 171, Devolucion = 0 where IdCedis = 3 and IdSurtido = 738
update Rejas set Surtido = 10, Devolucion = 10 where IdCedis = 3 and IdSurtido = 617
update Rejas set Surtido = 2, Devolucion = 2 where IdCedis = 3 and IdSurtido = 653
update Rejas set Surtido = 14, Devolucion = 0 where IdCedis = 3 and IdSurtido = 731
update Rejas set Surtido = 120, Devolucion = 125 where IdCedis = 3 and IdSurtido = 625
update Rejas set Surtido = 124, Devolucion = 127 where IdCedis = 3 and IdSurtido = 658
update Rejas set Surtido = 37, Devolucion = 124 where IdCedis = 3 and IdSurtido = 679
update Rejas set Surtido = 63, Devolucion = 105 where IdCedis = 3 and IdSurtido = 718
update Rejas set Surtido = 55, Devolucion = 92 where IdCedis = 3 and IdSurtido = 616
update Rejas set Surtido = 18, Devolucion = 18 where IdCedis = 3 and IdSurtido = 634
update Rejas set Surtido = 105, Devolucion = 112 where IdCedis = 3 and IdSurtido = 639
update Rejas set Surtido = 127, Devolucion = 141 where IdCedis = 3 and IdSurtido = 749
update Rejas set Surtido = 73, Devolucion = 0 where IdCedis = 3 and IdSurtido = 756
update Rejas set Surtido = 72, Devolucion = 74 where IdCedis = 3 and IdSurtido = 609
update Rejas set Surtido = 79, Devolucion = 79 where IdCedis = 3 and IdSurtido = 646
update Rejas set Surtido = 58, Devolucion = 57 where IdCedis = 3 and IdSurtido = 684
update Rejas set Surtido = 61, Devolucion = 76 where IdCedis = 3 and IdSurtido = 725
update Rejas set Surtido = 86, Devolucion = 106 where IdCedis = 3 and IdSurtido = 608
update Rejas set Surtido = 92, Devolucion = 94 where IdCedis = 3 and IdSurtido = 645
update Rejas set Surtido = 14, Devolucion = 88 where IdCedis = 3 and IdSurtido = 683
update Rejas set Surtido = 75, Devolucion = 75 where IdCedis = 3 and IdSurtido = 724
update Rejas set Surtido = 2, Devolucion = 0 where IdCedis = 3 and IdSurtido = 626
update Rejas set Surtido = 136, Devolucion = 127 where IdCedis = 3 and IdSurtido = 659
update Rejas set Surtido = 80, Devolucion = 79 where IdCedis = 3 and IdSurtido = 694
update Rejas set Surtido = 139, Devolucion = 144 where IdCedis = 3 and IdSurtido = 619
update Rejas set Surtido = 100, Devolucion = 102 where IdCedis = 3 and IdSurtido = 655
update Rejas set Surtido = 93, Devolucion = 76 where IdCedis = 3 and IdSurtido = 733
update Rejas set Surtido = 92, Devolucion = 0 where IdCedis = 3 and IdSurtido = 762
update Rejas set Surtido = 57, Devolucion = 57 where IdCedis = 3 and IdSurtido = 611
update Rejas set Surtido = 51, Devolucion = 52 where IdCedis = 3 and IdSurtido = 648
update Rejas set Surtido = 59, Devolucion = 62 where IdCedis = 3 and IdSurtido = 686
update Rejas set Surtido = 61, Devolucion = 61 where IdCedis = 3 and IdSurtido = 727
update Rejas set Surtido = 66, Devolucion = 60 where IdCedis = 3 and IdSurtido = 628
update Rejas set Surtido = 69, Devolucion = 74 where IdCedis = 3 and IdSurtido = 640
update Rejas set Surtido = 59, Devolucion = 71 where IdCedis = 3 and IdSurtido = 703
update Rejas set Surtido = 63, Devolucion = 0 where IdCedis = 3 and IdSurtido = 717
update Rejas set Surtido = 53, Devolucion = 61 where IdCedis = 3 and IdSurtido = 753
update Rejas set Surtido = 86, Devolucion = 86 where IdCedis = 3 and IdSurtido = 605
update Rejas set Surtido = 93, Devolucion = 104 where IdCedis = 3 and IdSurtido = 642
update Rejas set Surtido = 86, Devolucion = 88 where IdCedis = 3 and IdSurtido = 680
update Rejas set Surtido = 92, Devolucion = 100 where IdCedis = 3 and IdSurtido = 721
update Rejas set Surtido = 43, Devolucion = 51 where IdCedis = 3 and IdSurtido = 757
update Rejas set Surtido = 72, Devolucion = 72 where IdCedis = 3 and IdSurtido = 630
update Rejas set Surtido = 51, Devolucion = 53 where IdCedis = 3 and IdSurtido = 662
update Rejas set Surtido = 50, Devolucion = 56 where IdCedis = 3 and IdSurtido = 697
update Rejas set Surtido = 58, Devolucion = 58 where IdCedis = 3 and IdSurtido = 748
update Rejas set Surtido = 130, Devolucion = 131 where IdCedis = 3 and IdSurtido = 607
update Rejas set Surtido = 91, Devolucion = 115 where IdCedis = 3 and IdSurtido = 644
update Rejas set Surtido = 103, Devolucion = 105 where IdCedis = 3 and IdSurtido = 682
update Rejas set Surtido = 70, Devolucion = 75 where IdCedis = 3 and IdSurtido = 723
update Rejas set Surtido = 122, Devolucion = 0 where IdCedis = 3 and IdSurtido = 691
update Rejas set Surtido = 87, Devolucion = 87 where IdCedis = 3 and IdSurtido = 624
update Rejas set Surtido = 61, Devolucion = 63 where IdCedis = 3 and IdSurtido = 657
update Rejas set Surtido = 78, Devolucion = 79 where IdCedis = 3 and IdSurtido = 693
update Rejas set Surtido = 55, Devolucion = 55 where IdCedis = 3 and IdSurtido = 734
update Rejas set Surtido = 84, Devolucion = 103 where IdCedis = 3 and IdSurtido = 623
update Rejas set Surtido = 78, Devolucion = 101 where IdCedis = 3 and IdSurtido = 635
update Rejas set Surtido = 77, Devolucion = 93 where IdCedis = 3 and IdSurtido = 701
update Rejas set Surtido = 66, Devolucion = 64 where IdCedis = 3 and IdSurtido = 711
update Rejas set Surtido = 57, Devolucion = 0 where IdCedis = 3 and IdSurtido = 750
update Rejas set Surtido = 100, Devolucion = 116 where IdCedis = 3 and IdSurtido = 629
update Rejas set Surtido = 57, Devolucion = 65 where IdCedis = 3 and IdSurtido = 661
update Rejas set Surtido = 61, Devolucion = 70 where IdCedis = 3 and IdSurtido = 696
update Rejas set Surtido = 54, Devolucion = 54 where IdCedis = 3 and IdSurtido = 736
update Rejas set Surtido = 2, Devolucion = 0 where IdCedis = 3 and IdSurtido = 752
update Rejas set Surtido = 79, Devolucion = 79 where IdCedis = 3 and IdSurtido = 692
