//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransProdDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransProdDetalle()
        {
            this.TpdPun = new HashSet<TpdPun>();
            this.TrpPrp = new HashSet<TrpPrp>();
        }
    
        public string TransProdID { get; set; }
        public string TransProdDetalleID { get; set; }
        public string ProductoClave { get; set; }
        public string DescuentoClave { get; set; }
        public string PRGId { get; set; }
        public short TipoUnidad { get; set; }
        public int Partida { get; set; }
        public double Cantidad { get; set; }
        public Nullable<double> CantidadOriginal { get; set; }
        public double Precio { get; set; }
        public Nullable<double> PrecioBase { get; set; }
        public Nullable<short> TipoMotivo { get; set; }
        public Nullable<double> DescuentoPor { get; set; }
        public Nullable<double> DescuentoImp { get; set; }
        public double Subtotal { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public double Total { get; set; }
        public Nullable<short> Promocion { get; set; }
        public string PromocionClave { get; set; }
        public Nullable<short> TipoFaseIntSal { get; set; }
        public Nullable<double> PrestamoVendido { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioID { get; set; }
    
        public virtual ProductoUnidad ProductoUnidad { get; set; }
        public virtual Promocion Promocion1 { get; set; }
        public virtual TransProd TransProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TpdPun> TpdPun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrpPrp> TrpPrp { get; set; }
    }
}
