//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Vendedor = new HashSet<Vendedor>();
            this.SEMHist = new HashSet<SEMHist>();
            this.ProductoPrestamoCli = new HashSet<ProductoPrestamoCli>();
            this.ClienteEsquema = new HashSet<ClienteEsquema>();
            this.CLIConfNumCta = new HashSet<CLIConfNumCta>();
            this.ClienteDomicilio = new HashSet<ClienteDomicilio>();
            this.ClienteMensaje = new HashSet<ClienteMensaje>();
            this.ClientePago = new HashSet<ClientePago>();
            this.ClienteProducto = new HashSet<ClienteProducto>();
            this.ClienteSinVisitaRec = new HashSet<ClienteSinVisitaRec>();
            this.ClienteVentaMensual = new HashSet<ClienteVentaMensual>();
            this.CLIFormaVenta = new HashSet<CLIFormaVenta>();
            this.CLINoDesImp = new HashSet<CLINoDesImp>();
            this.ExcepcionFac = new HashSet<ExcepcionFac>();
            this.ExcepcionProductoPri = new HashSet<ExcepcionProductoPri>();
        }
    
        public string ClienteClave { get; set; }
        public string CNPId { get; set; }
        public string Clave { get; set; }
        public string IdElectronico { get; set; }
        public string IdFiscal { get; set; }
        public string RazonSocial { get; set; }
        public short TipoFiscal { get; set; }
        public short TipoImpuesto { get; set; }
        public string NombreContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public System.DateTime FechaRegistroSistema { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<double> LimiteCreditoDinero { get; set; }
        public string NombreCorto { get; set; }
        public short TipoEstado { get; set; }
        public Nullable<double> LimiteDescuento { get; set; }
        public Nullable<double> SaldoEfectivo { get; set; }
        public bool Prestamo { get; set; }
        public bool Exclusividad { get; set; }
        public Nullable<System.DateTime> VigExclusividad { get; set; }
        public bool ActualizaSaldoCheque { get; set; }
        public bool VencimientoVenta { get; set; }
        public Nullable<int> DiasVencimiento { get; set; }
        public Nullable<double> SaldoGarantia { get; set; }
        public Nullable<bool> Nuevo { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public bool DesgloseImpuesto { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<short> TipoComplemento { get; set; }
        public Nullable<short> TipoEstadoCom { get; set; }
        public Nullable<bool> EnvioAutomatico { get; set; }
        public string Servidor { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public string Puerto { get; set; }
        public bool ExigirOrdenCompra { get; set; }
        public bool ExigirPedidoAdicional { get; set; }
        public string FormatoPedidoAdicional { get; set; }
        public bool FacturacionMasiva { get; set; }
        public bool ExigirTomaInvMer { get; set; }
        public Nullable<int> LimiteEnvase { get; set; }
        public Nullable<bool> ValidarLimEnvase { get; set; }
        public bool ValidaFolNeg { get; set; }
        public bool GrabarDecXML { get; set; }
        public string NumeroSAP { get; set; }
        public string AlmacenID { get; set; }
        public short PublicoGeneral { get; set; }
        public short FacturaFolioVenta { get; set; }
        public short FacturaVentasMensual { get; set; }
        public Nullable<short> TipoCamion { get; set; }
        public string ZonaClave { get; set; }
        public short BonificacionMasiva { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioID { get; set; }
        public short AseguramientoGPS { get; set; }
        public Nullable<short> UsoCFDI { get; set; }
        public string DatosExtra { get; set; }
        public Nullable<System.DateTime> FechaInactivacion { get; set; }
        public Nullable<short> MotivoInactivacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendedor> Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEMHist> SEMHist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoPrestamoCli> ProductoPrestamoCli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteEsquema> ClienteEsquema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIConfNumCta> CLIConfNumCta { get; set; }
        public virtual ClienteAcumulados ClienteAcumulados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteDomicilio> ClienteDomicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteMensaje> ClienteMensaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientePago> ClientePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteProducto> ClienteProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteSinVisitaRec> ClienteSinVisitaRec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteVentaMensual> ClienteVentaMensual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIFormaVenta> CLIFormaVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLINoDesImp> CLINoDesImp { get; set; }
        public virtual Zona Zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcepcionFac> ExcepcionFac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcepcionProductoPri> ExcepcionProductoPri { get; set; }
    }
}
