//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolioUsuario
    {
        public string FolioID { get; set; }
        public string VendedorID { get; set; }
        public int CantidadDia { get; set; }
        public short TipoReservacion { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioID { get; set; }
    
        public virtual Folio Folio { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
