SET NOCOUNT ON
IF EXISTS (SELECT * FROM sys.objects WHERE TYPE='P' AND NAME='stpr_Cobranza_28')
	DROP PROCEDURE [dbo].[stpr_Cobranza_28]
SET NOCOUNT OFF
/*go*/go

CREATE PROCEDURE [dbo].[stpr_Cobranza_28]
@FILTROCEDI AS VARCHAR(20),
@FILTRORUTAS AS VARCHAR(MAX) = NULL,
@FILTROFECHAINI AS VARCHAR(10),
@FILTROFECHAFIN AS VARCHAR(10)
AS
	SET NOCOUNT ON
	DECLARE
		@CEDI AS VARCHAR(20),
		@RUTAS AS VARCHAR(MAX) = NULL,
		@FECHAINI AS DATETIME,
		@FECHAFIN AS DATETIME

	IF NOT COALESCE(@FILTROCEDI,'') = ''
		SET @CEDI = @FILTROCEDI

	IF NOT COALESCE(@FILTRORUTAS,'') = ''
		SET @RUTAS = @FILTRORUTAS

	IF NOT COALESCE(@FILTROFECHAINI,'') = ''
		SET @FECHAINI = @FILTROFECHAINI

	IF NOT COALESCE(@FILTROFECHAFIN,'') = ''
		SET @FECHAFIN = @FILTROFECHAFIN

	SELECT DISTINCT
		RUT.RUTClave + ' - ' + VEN.Nombre AS [Ruta|GROUPER],
		ABN.Folio AS [Folio Abono], ABN.FechaAbono AS [Fecha Abono|FORMAT%d], dbo.[fn_CharLTrim]('0', ISNULL(TVA.PedidoAdicional, TRP.Folio)) AS [Folio SAP], ABT.Importe AS [Monto|FORMAT&$],
		VAD.Descripcion AS [Forma Pago], (CASE WHEN ABD.TipoBanco = 0 THEN '' ELSE BANCO.Descripcion END) AS [Banco], ISNULL(ABD.Referencia, '') AS Referencia, CLI.Clave AS [Cliente], CLI.RazonSocial AS [Nombre Cliente],
		ISNULL(ABD.Observaciones, '') AS Observaciones,
		RUT.RUTClave--, VEN.Nombre AS Vendedor, RUT.AlmacenID AS OrgVentas
	FROM AbnTrp ABT
		INNER JOIN TransProd TRP ON ABT.TransProdID = TRP.TransProdID
		INNER JOIN Abono ABN ON ABT.ABNId = ABN.ABNId
		INNER JOIN ABNDetalle ABD ON ABN.ABNId = ABD.ABNId
		INNER JOIN VAVDescripcion VAD ON VAD.VARCodigo = 'PAGO' AND VAD.VAVClave = ABD.TipoPago AND VAD.VADTipoLenguaje = 'EM'
		INNER JOIN Visita VIS ON VIS.VisitaClave = ISNULL(ABT.VisitaClave, ABN.VisitaClave) AND VIS.DiaClave = ISNULL(ABT.DiaClave, ABN.DiaClave)
		INNER JOIN Cliente CLI ON CLI.ClienteClave = VIS.ClienteClave
		INNER JOIN Vendedor VEN ON VIS.VendedorID = VEN.VendedorID
		INNER JOIN Ruta RUT ON RUT.RUTClave = VIS.RUTClave
		INNER JOIN Almacen ALM ON RUT.AlmacenID = ALM.AlmacenID
		LEFT JOIN VAVDescripcion BANCO ON BANCO.VARCodigo ='TBANCO' AND BANCO.VAVClave = ABD.TipoBanco AND BANCO.VADTipoLenguaje = 'EM'
		LEFT JOIN TRPVtaAcreditada TVA ON TRP.TransProdID = TVA.TransProdID
	WHERE ((VIS.RUTClave IN (SELECT Datos FROM [dbo].[FNSplit](@RUTAS, ','))) OR @RUTAS IS NULL) 
		AND CONVERT(DATETIME, CONVERT(VARCHAR(20), ABT.FechaHora, 112)) BETWEEN @FECHAINI AND @FECHAFIN
		AND ALM.AlmacenID = @CEDI AND ABT.Importe > 0
	ORDER BY RUT.RUTClave, CLI.Clave, [Folio SAP]

	SET NOCOUNT OFF
/*go*/go