--	if exists(select IdSurtido from VendedoresSaldos where IdCedis = @IdCedis and IdSurtido = @IdSurtido and IdTipoSaldo = 'EF')
--		begin
--			select @Importe = isnull( sum(IdDenominacion * Cantidad), 0) 
--				from SurtidosDenominacion 
--			where IdCedis = @IdCedis and IdSurtido = @IdSurtido 
--
--			select @Importe = isnull(@Importe,0) - isnull(sum(Total),0)
--			from VentasDetalle
--			where VentasDetalle.IdCedis = @IdCedis and VentasDetalle.IdSurtido = @IdSurtido
--			and IdTipoVenta = 1
--
--			update VendedoresSaldos set Saldo = @Importe, SaldoActual = SaldoAnterior + @Importe
--			where IdCedis = @IdCedis and IdSurtido = @IdSurtido and IdTipoSaldo = 'EF'
--		end
--	else
--		begin
--			insert into VendedoresSaldos 
--			select @IdCedis, @IdSurtido, IdRuta, 'EF', IdVendedor, Surtidos.Fecha, 0, 0, 0
--			from Surtidos 
--			inner join SurtidosVendedor on Surtidos.IdCedis = SurtidosVendedor.IdCedis and Surtidos.IdSurtido = SurtidosVendedor.IdSurtido
--			where Surtidos.IdCedis = @IdCedis and Surtidos.IdSurtido = @IdSurtido 
--
--			declare VendedoresCursor cursor for
--				select IdVendedor 
--				from Surtidos 
--				inner join SurtidosVendedor on Surtidos.IdCedis = SurtidosVendedor.IdCedis and Surtidos.IdSurtido = SurtidosVendedor.IdSurtido
--				where Surtidos.IdCedis = @IdCedis and Surtidos.IdSurtido = @IdSurtido
--			open VendedoresCursor 
--			
--			fetch next from VendedoresCursor into @IdVendedor
--			while (@@fetch_status = 0)
--			begin
--
--				select Top 1 @Importe = isnull(SaldoActual, 0)
--				from VendedoresSaldos 
--				where IdCedis = @IdCedis and IdVendedor = @IdVendedor and IdSurtido <> @IdSurtido
--				order by Fecha desc
--				
--				update VendedoresSaldos set SaldoAnterior = @Importe
--				where IdCedis = @IdCedis and IdSurtido = @IdSurtido and IdVendedor = @IdVendedor and IdTipoSaldo = 'EF'
--
--				fetch next from VendedoresCursor into @IdVendedor
--			end
--			close VendedoresCursor 
--			deallocate VendedoresCursor		
--
--			select @Importe = isnull( sum(IdDenominacion * Cantidad), 0) 
--				from SurtidosDenominacion 
--			where IdCedis = @IdCedis and IdSurtido = @IdSurtido 
--
--			select @Importe = isnull(@Importe,0) - isnull(sum(Total),0)
--			from VentasDetalle
--			where VentasDetalle.IdCedis = @IdCedis and VentasDetalle.IdSurtido = @IdSurtido
--			and IdTipoVenta = 1
--
--			update VendedoresSaldos set Saldo = @Importe, SaldoActual = SaldoAnterior + @Importe
--			where IdCedis = @IdCedis and IdSurtido = @IdSurtido and IdTipoSaldo = 'EF'
--
--		end
