//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RouteEntities : DbContext
    {
        public RouteEntities()
            : base("name=RouteEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Actividad>().ToTable("Actividad");
            modelBuilder.Entity<AgendaVendedor>().ToTable("AgendaVendedor");
            modelBuilder.Entity<Almacen>().ToTable("Almacen");
            modelBuilder.Entity<AlmacenProducto>().ToTable("AlmacenProducto");
            modelBuilder.Entity<Camion>().ToTable("Camion");
            modelBuilder.Entity<CamionVendedor>().ToTable("CamionVendedor");
            modelBuilder.Entity<CLIConfNumCta>().ToTable("CLIConfNumCta");
            modelBuilder.Entity<Cliente>().ToTable("Cliente");
            modelBuilder.Entity<ClienteAcumulados>().ToTable("ClienteAcumulados");
            modelBuilder.Entity<ClienteDomicilio>().ToTable("ClienteDomicilio");
            modelBuilder.Entity<ClienteEsquema>().ToTable("ClienteEsquema");
            modelBuilder.Entity<ClienteMensaje>().ToTable("ClienteMensaje");
            modelBuilder.Entity<ClientePago>().ToTable("ClientePago");
            modelBuilder.Entity<ClienteProducto>().ToTable("ClienteProducto");
            modelBuilder.Entity<ClienteSinVisitaRec>().ToTable("ClienteSinVisitaRec");
            modelBuilder.Entity<ClienteVentaMensual>().ToTable("ClienteVentaMensual");
            modelBuilder.Entity<CLIFormaVenta>().ToTable("CLIFormaVenta");
            modelBuilder.Entity<CLINoDesImp>().ToTable("CLINoDesImp");
            modelBuilder.Entity<ConfigParametro>().ToTable("ConfigParametro");
            modelBuilder.Entity<Configuracion>().ToTable("Configuracion");
            modelBuilder.Entity<ConfiguracionRecibo>().ToTable("ConfiguracionRecibo");
            modelBuilder.Entity<CONHist>().ToTable("CONHist");
            modelBuilder.Entity<CORTabla>().ToTable("CORTabla");
            modelBuilder.Entity<COTCampo>().ToTable("COTCampo");
            modelBuilder.Entity<CUOEsquema>().ToTable("CUOEsquema");
            modelBuilder.Entity<DESDetalle>().ToTable("DESDetalle");
            modelBuilder.Entity<Dia>().ToTable("Dia");
            modelBuilder.Entity<Esquema>().ToTable("Esquema");
            modelBuilder.Entity<ExcepcionFac>().ToTable("ExcepcionFac");
            modelBuilder.Entity<ExcepcionProductoPri>().ToTable("ExcepcionProductoPri");
            modelBuilder.Entity<Folio>().ToTable("Folio");
            modelBuilder.Entity<FolioCEDI>().ToTable("FolioCEDI");
            modelBuilder.Entity<FolioDetalle>().ToTable("FolioDetalle");
            modelBuilder.Entity<FolioUsuario>().ToTable("FolioUsuario");
            modelBuilder.Entity<Frecuencia>().ToTable("Frecuencia");
            modelBuilder.Entity<Impuesto>().ToTable("Impuesto");
            modelBuilder.Entity<ImpuestoEsquema>().ToTable("ImpuestoEsquema");
            modelBuilder.Entity<Interfaz>().ToTable("Interfaz");
            modelBuilder.Entity<IntPer>().ToTable("IntPer");
            modelBuilder.Entity<IntUsu>().ToTable("IntUsu");
            modelBuilder.Entity<MDBMensaje>().ToTable("MDBMensaje");
            modelBuilder.Entity<MENDetalle>().ToTable("MENDetalle");
            modelBuilder.Entity<Mensaje>().ToTable("Mensaje");
            modelBuilder.Entity<Modulo>().ToTable("Modulo");
            modelBuilder.Entity<ModuloEsquema>().ToTable("ModuloEsquema");
            modelBuilder.Entity<ModuloMensaje>().ToTable("ModuloMensaje");
            modelBuilder.Entity<ModuloMov>().ToTable("ModuloMov");
            modelBuilder.Entity<ModuloMovDetalle>().ToTable("ModuloMovDetalle");
            modelBuilder.Entity<ModuloTerm>().ToTable("ModuloTerm");
            modelBuilder.Entity<Moneda>().ToTable("Moneda");
            modelBuilder.Entity<MONRedondeoVig>().ToTable("MONRedondeoVig");
            modelBuilder.Entity<MONTipoCambioVig>().ToTable("MONTipoCambioVig");
            modelBuilder.Entity<MOTConfiguracion>().ToTable("MOTConfiguracion");
            modelBuilder.Entity<Perfil>().ToTable("Perfil");
            modelBuilder.Entity<PoliticaContrasena>().ToTable("PoliticaContrasena");
            modelBuilder.Entity<PoliticaContrasenaHist>().ToTable("PoliticaContrasenaHist");
            modelBuilder.Entity<Precio>().ToTable("Precio");
            modelBuilder.Entity<PrecioClienteEsquema>().ToTable("PrecioClienteEsquema");
            modelBuilder.Entity<PrecioProductoVig>().ToTable("PrecioProductoVig");
            modelBuilder.Entity<Producto>().ToTable("Producto");
            modelBuilder.Entity<ProductoCompetencia>().ToTable("ProductoCompetencia");
            modelBuilder.Entity<ProductoDetalle>().ToTable("ProductoDetalle");
            modelBuilder.Entity<ProductoEpicor>().ToTable("ProductoEpicor");
            modelBuilder.Entity<ProductoEquivalente>().ToTable("ProductoEquivalente");
            modelBuilder.Entity<ProductoEquivalenteCompetencia>().ToTable("ProductoEquivalenteCompetencia");
            modelBuilder.Entity<ProductoEsquema>().ToTable("ProductoEsquema");
            modelBuilder.Entity<ProductoImpuesto>().ToTable("ProductoImpuesto");
            modelBuilder.Entity<ProductoNegado>().ToTable("ProductoNegado");
            modelBuilder.Entity<ProductoPrestamoCli>().ToTable("ProductoPrestamoCli");
            modelBuilder.Entity<ProductoPrioritarioEsq>().ToTable("ProductoPrioritarioEsq");
            modelBuilder.Entity<ProductoUnidad>().ToTable("ProductoUnidad");
            modelBuilder.Entity<Promocion>().ToTable("Promocion");
            modelBuilder.Entity<PromocionAplicacion>().ToTable("PromocionAplicacion");
            modelBuilder.Entity<PromocionDetalle>().ToTable("PromocionDetalle");
            modelBuilder.Entity<PromocionEsquema>().ToTable("PromocionEsquema");
            modelBuilder.Entity<PromocionEsquemaExcep>().ToTable("PromocionEsquemaExcep");
            modelBuilder.Entity<PromocionModulo>().ToTable("PromocionModulo");
            modelBuilder.Entity<PromocionProducto>().ToTable("PromocionProducto");
            modelBuilder.Entity<PromocionRegla>().ToTable("PromocionRegla");
            modelBuilder.Entity<Recibo>().ToTable("Recibo");
            modelBuilder.Entity<Ruta>().ToTable("Ruta");
            modelBuilder.Entity<RutaProductoEsquema>().ToTable("RutaProductoEsquema");
            modelBuilder.Entity<RutaPunto>().ToTable("RutaPunto");
            modelBuilder.Entity<RutasOxxo>().ToTable("RutasOxxo");
            modelBuilder.Entity<RuteoDinamico>().ToTable("RuteoDinamico");
            modelBuilder.Entity<Secuencia>().ToTable("Secuencia");
            modelBuilder.Entity<SEMHist>().ToTable("SEMHist");
            modelBuilder.Entity<SubEmpresa>().ToTable("SubEmpresa");
            modelBuilder.Entity<SupervisorRuta>().ToTable("SupervisorRuta");
            modelBuilder.Entity<Terminal>().ToTable("Terminal");
            modelBuilder.Entity<TerminalSerial>().ToTable("TerminalSerial");
            modelBuilder.Entity<TerminalVersion>().ToTable("TerminalVersion");
            modelBuilder.Entity<TpdPun>().ToTable("TpdPun");
            modelBuilder.Entity<TransProd>().ToTable("TransProd");
            modelBuilder.Entity<TransProdDetalle>().ToTable("TransProdDetalle");
            modelBuilder.Entity<TrpPrp>().ToTable("TrpPrp");
            modelBuilder.Entity<Usuario>().ToTable("Usuario");
            modelBuilder.Entity<UsuarioAlmacen>().ToTable("UsuarioAlmacen");
            modelBuilder.Entity<ValorReferencia>().ToTable("ValorReferencia");
            modelBuilder.Entity<VARValor>().ToTable("VARValor");
            modelBuilder.Entity<VAVDescripcion>().ToTable("VAVDescripcion");
            modelBuilder.Entity<VENCentroDistHist>().ToTable("VENCentroDistHist");
            modelBuilder.Entity<Vendedor>().ToTable("Vendedor");
            modelBuilder.Entity<VendedorDescuento>().ToTable("VendedorDescuento");
            modelBuilder.Entity<VendedorEsquema>().ToTable("VendedorEsquema");
            modelBuilder.Entity<VendedorJornada>().ToTable("VendedorJornada");
            modelBuilder.Entity<VendedorMensaje>().ToTable("VendedorMensaje");
            modelBuilder.Entity<VenRut>().ToTable("VenRut");
            modelBuilder.Entity<Visita>().ToTable("Visita");
            modelBuilder.Entity<Zona>().ToTable("Zona");
            modelBuilder.Entity<ZonaPunto>().ToTable("ZonaPunto");
        }

        public virtual DbSet<MENDetalle> MENDetalle { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<ValorReferencia> ValorReferencia { get; set; }
        public virtual DbSet<VARValor> VARValor { get; set; }
        public virtual DbSet<VAVDescripcion> VAVDescripcion { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<CONHist> CONHist { get; set; }
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Interfaz> Interfaz { get; set; }
        public virtual DbSet<IntPer> IntPer { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<AlmacenProducto> AlmacenProducto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioAlmacen> UsuarioAlmacen { get; set; }
        public virtual DbSet<PoliticaContrasena> PoliticaContrasena { get; set; }
        public virtual DbSet<PoliticaContrasenaHist> PoliticaContrasenaHist { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<RutaPunto> RutaPunto { get; set; }
        public virtual DbSet<RutasOxxo> RutasOxxo { get; set; }
        public virtual DbSet<Terminal> Terminal { get; set; }
        public virtual DbSet<TerminalSerial> TerminalSerial { get; set; }
        public virtual DbSet<TerminalVersion> TerminalVersion { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VendedorDescuento> VendedorDescuento { get; set; }
        public virtual DbSet<VendedorEsquema> VendedorEsquema { get; set; }
        public virtual DbSet<VendedorJornada> VendedorJornada { get; set; }
        public virtual DbSet<VendedorMensaje> VendedorMensaje { get; set; }
        public virtual DbSet<VenRut> VenRut { get; set; }
        public virtual DbSet<SupervisorRuta> SupervisorRuta { get; set; }
        public virtual DbSet<IntUsu> IntUsu { get; set; }
        public virtual DbSet<Camion> Camion { get; set; }
        public virtual DbSet<CamionVendedor> CamionVendedor { get; set; }
        public virtual DbSet<SubEmpresa> SubEmpresa { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<SEMHist> SEMHist { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<PrecioClienteEsquema> PrecioClienteEsquema { get; set; }
        public virtual DbSet<PrecioProductoVig> PrecioProductoVig { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoUnidad> ProductoUnidad { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<Impuesto> Impuesto { get; set; }
        public virtual DbSet<Esquema> Esquema { get; set; }
        public virtual DbSet<ProductoCompetencia> ProductoCompetencia { get; set; }
        public virtual DbSet<ProductoDetalle> ProductoDetalle { get; set; }
        public virtual DbSet<ProductoEpicor> ProductoEpicor { get; set; }
        public virtual DbSet<ProductoEquivalente> ProductoEquivalente { get; set; }
        public virtual DbSet<ProductoEquivalenteCompetencia> ProductoEquivalenteCompetencia { get; set; }
        public virtual DbSet<ProductoEsquema> ProductoEsquema { get; set; }
        public virtual DbSet<ProductoImpuesto> ProductoImpuesto { get; set; }
        public virtual DbSet<ProductoNegado> ProductoNegado { get; set; }
        public virtual DbSet<ProductoPrestamoCli> ProductoPrestamoCli { get; set; }
        public virtual DbSet<ProductoPrioritarioEsq> ProductoPrioritarioEsq { get; set; }
        public virtual DbSet<ConfigParametro> ConfigParametro { get; set; }
        public virtual DbSet<ClienteEsquema> ClienteEsquema { get; set; }
        public virtual DbSet<CUOEsquema> CUOEsquema { get; set; }
        public virtual DbSet<DESDetalle> DESDetalle { get; set; }
        public virtual DbSet<ImpuestoEsquema> ImpuestoEsquema { get; set; }
        public virtual DbSet<ModuloEsquema> ModuloEsquema { get; set; }
        public virtual DbSet<PromocionDetalle> PromocionDetalle { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<MONRedondeoVig> MONRedondeoVig { get; set; }
        public virtual DbSet<MONTipoCambioVig> MONTipoCambioVig { get; set; }
        public virtual DbSet<CLIConfNumCta> CLIConfNumCta { get; set; }
        public virtual DbSet<ClienteAcumulados> ClienteAcumulados { get; set; }
        public virtual DbSet<ClienteDomicilio> ClienteDomicilio { get; set; }
        public virtual DbSet<ClienteMensaje> ClienteMensaje { get; set; }
        public virtual DbSet<ClientePago> ClientePago { get; set; }
        public virtual DbSet<ClienteProducto> ClienteProducto { get; set; }
        public virtual DbSet<ClienteSinVisitaRec> ClienteSinVisitaRec { get; set; }
        public virtual DbSet<ClienteVentaMensual> ClienteVentaMensual { get; set; }
        public virtual DbSet<CLIFormaVenta> CLIFormaVenta { get; set; }
        public virtual DbSet<CLINoDesImp> CLINoDesImp { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<ZonaPunto> ZonaPunto { get; set; }
        public virtual DbSet<ModuloTerm> ModuloTerm { get; set; }
        public virtual DbSet<MOTConfiguracion> MOTConfiguracion { get; set; }
        public virtual DbSet<Frecuencia> Frecuencia { get; set; }
        public virtual DbSet<Secuencia> Secuencia { get; set; }
        public virtual DbSet<VENCentroDistHist> VENCentroDistHist { get; set; }
        public virtual DbSet<MDBMensaje> MDBMensaje { get; set; }
        public virtual DbSet<ModuloMovDetalle> ModuloMovDetalle { get; set; }
        public virtual DbSet<RutaProductoEsquema> RutaProductoEsquema { get; set; }
        public virtual DbSet<ExcepcionFac> ExcepcionFac { get; set; }
        public virtual DbSet<ExcepcionProductoPri> ExcepcionProductoPri { get; set; }
        public virtual DbSet<ModuloMov> ModuloMov { get; set; }
        public virtual DbSet<ModuloMensaje> ModuloMensaje { get; set; }
        public virtual DbSet<TransProd> TransProd { get; set; }
        public virtual DbSet<TransProdDetalle> TransProdDetalle { get; set; }
        public virtual DbSet<Folio> Folio { get; set; }
        public virtual DbSet<FolioDetalle> FolioDetalle { get; set; }
        public virtual DbSet<Recibo> Recibo { get; set; }
        public virtual DbSet<FolioUsuario> FolioUsuario { get; set; }
        public virtual DbSet<CORTabla> CORTabla { get; set; }
        public virtual DbSet<COTCampo> COTCampo { get; set; }
        public virtual DbSet<ConfiguracionRecibo> ConfiguracionRecibo { get; set; }
        public virtual DbSet<TpdPun> TpdPun { get; set; }
        public virtual DbSet<TrpPrp> TrpPrp { get; set; }
        public virtual DbSet<PromocionAplicacion> PromocionAplicacion { get; set; }
        public virtual DbSet<PromocionEsquema> PromocionEsquema { get; set; }
        public virtual DbSet<PromocionEsquemaExcep> PromocionEsquemaExcep { get; set; }
        public virtual DbSet<PromocionModulo> PromocionModulo { get; set; }
        public virtual DbSet<PromocionProducto> PromocionProducto { get; set; }
        public virtual DbSet<PromocionRegla> PromocionRegla { get; set; }
        public virtual DbSet<AgendaVendedor> AgendaVendedor { get; set; }
        public virtual DbSet<Dia> Dia { get; set; }
        public virtual DbSet<FolioCEDI> FolioCEDI { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<RuteoDinamico> RuteoDinamico { get; set; }
    }
}
