//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conteo
    {
        public Conteo()
        {
            this.ConteoAsignacion = new HashSet<ConteoAsignacion>();
            this.ConteoConfig = new HashSet<ConteoConfig>();
            this.ConteoDetalle = new HashSet<ConteoDetalle>();
        }
    
        public string CONClave { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> Mes { get; set; }
        public string ALMClave { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
        public string Clave { get; set; }
        public string SUCClave { get; set; }
    
        public virtual ICollection<ConteoAsignacion> ConteoAsignacion { get; set; }
        public virtual ICollection<ConteoConfig> ConteoConfig { get; set; }
        public virtual ICollection<ConteoDetalle> ConteoDetalle { get; set; }
    }
}
