//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovUbc
    {
        public string MOVClave { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> Mes { get; set; }
        public string SUCClave { get; set; }
        public string ALMClave { get; set; }
        public string UBCClaveO { get; set; }
        public string UBCClaveD { get; set; }
        public string PROClave { get; set; }
        public Nullable<int> TipoMov { get; set; }
        public Nullable<int> Motivo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> TipoEstado { get; set; }
        public string Nota { get; set; }
        public string Referencia { get; set; }
        public string Plataforma { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
