//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboAlmacen
    {
        public ReciboAlmacen()
        {
            this.ReciboAlmacenD = new HashSet<ReciboAlmacenD>();
            this.ReciboSobrante = new HashSet<ReciboSobrante>();
            this.ReciboAlmacenT = new HashSet<ReciboAlmacenT>();
        }
    
        public string IdRecibo { get; set; }
        public string ALMClave { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaRecibo { get; set; }
        public Nullable<int> NoDocumentos { get; set; }
        public Nullable<decimal> CantidadSolicitada { get; set; }
        public Nullable<decimal> CantidadRecibida { get; set; }
        public string Anden { get; set; }
        public string Chofer { get; set; }
        public string Transporte { get; set; }
        public string Notas { get; set; }
        public Nullable<System.DateTime> FechaFinalizacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> EnvioSAP { get; set; }
        public Nullable<System.DateTime> FechaEnvioSAP { get; set; }
        public string FolioSAP { get; set; }
        public string MUsuarioId { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual ICollection<ReciboAlmacenD> ReciboAlmacenD { get; set; }
        public virtual ICollection<ReciboSobrante> ReciboSobrante { get; set; }
        public virtual ICollection<ReciboAlmacenT> ReciboAlmacenT { get; set; }
    }
}
