//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaPunto
    {
        public string RutaPuntoID { get; set; }
        public string RUTClave { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioID { get; set; }
    
        public virtual Ruta Ruta { get; set; }
    }
}
