//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public string CTEClave { get; set; }
        public string Clave { get; set; }
        public string Alterno { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string NombreCorto { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> TPersona { get; set; }
        public string id_Fiscal { get; set; }
        public string CURP { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public Nullable<int> DiasCredito { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Contacto { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Email { get; set; }
        public Nullable<int> TipoImpuesto { get; set; }
        public Nullable<bool> DesglosaIVA { get; set; }
        public string GLN { get; set; }
        public string CtaContable { get; set; }
        public Nullable<int> TipoCanal { get; set; }
        public string PREClave { get; set; }
        public Nullable<int> Responsable { get; set; }
        public Nullable<int> Ramo { get; set; }
        public Nullable<decimal> Puntos { get; set; }
        public Nullable<int> DescuentoDirecto { get; set; }
        public Nullable<int> DescuentoPostVenta { get; set; }
        public string COMClave { get; set; }
        public string Vendedor { get; set; }
        public string ClienteSAP { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<bool> Baja { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
        public Nullable<int> TipoOrigen { get; set; }
        public string NumRegIdTrib { get; set; }
    
        public virtual Compania Compania { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
