//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevCompra
    {
        public string DEVClave { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Folio { get; set; }
        public string Motivo { get; set; }
        public string PRVClave { get; set; }
        public string Factura { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public string Notas { get; set; }
        public string SUCClave { get; set; }
        public string ALMClave { get; set; }
        public string Atendio { get; set; }
        public string Autorizo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> EnvioSAP { get; set; }
        public Nullable<System.DateTime> FechaEnvioSAP { get; set; }
        public string UBCClave { get; set; }
        public string PICClave { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
