//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVALM
    {
        public string MVAClave { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Motivo { get; set; }
        public string Solicita { get; set; }
        public string ALMClave { get; set; }
        public string ALMDestino { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Registro { get; set; }
        public string Autorizo { get; set; }
        public string Notas { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string SUCClave { get; set; }
        public string PICClave { get; set; }
        public Nullable<System.DateTime> fechaEfectiva { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UBCClave { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Picking Picking { get; set; }
    }
}
