//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public Orden()
        {
            this.OrdenDetalle = new HashSet<OrdenDetalle>();
        }
    
        public string ORDClave { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> Mes { get; set; }
        public string SUCClave { get; set; }
        public string ALMClave { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Registro { get; set; }
        public string PRVClave { get; set; }
        public string Motivo { get; set; }
        public string Solicita { get; set; }
        public string Nota { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> ImpuestoTot { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<bool> Baja { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
        public virtual ICollection<OrdenDetalle> OrdenDetalle { get; set; }
    }
}
