//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picking
    {
        public Picking()
        {
            this.MOVALM = new HashSet<MOVALM>();
            this.Traslado = new HashSet<Traslado>();
            this.Venta = new HashSet<Venta>();
        }
    
        public string PICClave { get; set; }
        public Nullable<int> Estado { get; set; }
        public string IP { get; set; }
        public string MUsuarioId { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
    
        public virtual ICollection<MOVALM> MOVALM { get; set; }
        public virtual Picking Picking1 { get; set; }
        public virtual Picking Picking2 { get; set; }
        public virtual ICollection<Traslado> Traslado { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
