//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prd_exist_uba
    {
        public string PROClave { get; set; }
        public string UBCClave { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public Nullable<decimal> Apartado { get; set; }
        public Nullable<decimal> Bloqueado { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
