//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalProducto
    {
        public string SUCClave { get; set; }
        public string PROClave { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public Nullable<decimal> Maximo { get; set; }
        public Nullable<decimal> Reorden { get; set; }
        public Nullable<int> TRotacion { get; set; }
        public Nullable<decimal> CostoVigente { get; set; }
        public Nullable<int> TipoImpuesto { get; set; }
        public Nullable<System.DateTime> MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
