'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DigitalInvoiceC
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://digitalinvoice.com.mx/WSDI", ConfigurationName:="DigitalInvoiceC.ITimbrado")>  _
    Public Interface ITimbrado
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/Timbrar", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function Timbrar(ByVal comprobanteBytesZipped() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbre", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbre(ByVal comprobante() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTest", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarTest(ByVal comprobanteBytesZipped() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTest", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbreTest(ByVal comprobante() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAck", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarAck(ByVal comprobante() As Byte) As WebServicesCFDI.TimbradoReference.TimbradoCFDIResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/ObtenerAck", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/ObtenerAckResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function ObtenerAck(ByVal UUID As String, ByVal rfcEmisor As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbre", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbre(ByVal comprobante() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreUUID", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreUUIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbreUUID(ByVal UUID As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbres", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbres(ByVal UUIDs() As String) As Byte()()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarTestBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbreTestBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarAckBase64(ByVal comprobante As String) As WebServicesCFDI.TimbradoReference.TimbradoCFDIResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbreBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64UUID", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64UUIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbreBase64UUID(ByVal UUID As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbresBase64(ByVal UUIDs() As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WebServicesCFDI.TimbradoReference.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbreBase64(ByVal comprobante As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITimbradoChannel
        Inherits DigitalInvoiceC.ITimbrado, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TimbradoClient
        Inherits System.ServiceModel.ClientBase(Of DigitalInvoiceC.ITimbrado)
        Implements DigitalInvoiceC.ITimbrado
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Timbrar(ByVal comprobanteBytesZipped() As Byte) As Byte() Implements DigitalInvoiceC.ITimbrado.Timbrar
            Return MyBase.Channel.Timbrar(comprobanteBytesZipped)
        End Function
        
        Public Function TimbrarSoloTimbre(ByVal comprobante() As Byte) As Byte() Implements DigitalInvoiceC.ITimbrado.TimbrarSoloTimbre
            Return MyBase.Channel.TimbrarSoloTimbre(comprobante)
        End Function
        
        Public Function TimbrarTest(ByVal comprobanteBytesZipped() As Byte) As Byte() Implements DigitalInvoiceC.ITimbrado.TimbrarTest
            Return MyBase.Channel.TimbrarTest(comprobanteBytesZipped)
        End Function
        
        Public Function TimbrarSoloTimbreTest(ByVal comprobante() As Byte) As Byte() Implements DigitalInvoiceC.ITimbrado.TimbrarSoloTimbreTest
            Return MyBase.Channel.TimbrarSoloTimbreTest(comprobante)
        End Function
        
        Public Function TimbrarAck(ByVal comprobante() As Byte) As WebServicesCFDI.TimbradoReference.TimbradoCFDIResult Implements DigitalInvoiceC.ITimbrado.TimbrarAck
            Return MyBase.Channel.TimbrarAck(comprobante)
        End Function
        
        Public Function ObtenerAck(ByVal UUID As String, ByVal rfcEmisor As String) As String Implements DigitalInvoiceC.ITimbrado.ObtenerAck
            Return MyBase.Channel.ObtenerAck(UUID, rfcEmisor)
        End Function
        
        Public Function RecuperarTimbre(ByVal comprobante() As Byte) As Byte() Implements DigitalInvoiceC.ITimbrado.RecuperarTimbre
            Return MyBase.Channel.RecuperarTimbre(comprobante)
        End Function
        
        Public Function RecuperarTimbreUUID(ByVal UUID As String) As Byte() Implements DigitalInvoiceC.ITimbrado.RecuperarTimbreUUID
            Return MyBase.Channel.RecuperarTimbreUUID(UUID)
        End Function
        
        Public Function RecuperarTimbres(ByVal UUIDs() As String) As Byte()() Implements DigitalInvoiceC.ITimbrado.RecuperarTimbres
            Return MyBase.Channel.RecuperarTimbres(UUIDs)
        End Function
        
        Public Function TimbrarBase64(ByVal comprobante As String) As String Implements DigitalInvoiceC.ITimbrado.TimbrarBase64
            Return MyBase.Channel.TimbrarBase64(comprobante)
        End Function
        
        Public Function TimbrarTestBase64(ByVal comprobante As String) As String Implements DigitalInvoiceC.ITimbrado.TimbrarTestBase64
            Return MyBase.Channel.TimbrarTestBase64(comprobante)
        End Function
        
        Public Function TimbrarSoloTimbreTestBase64(ByVal comprobante As String) As String Implements DigitalInvoiceC.ITimbrado.TimbrarSoloTimbreTestBase64
            Return MyBase.Channel.TimbrarSoloTimbreTestBase64(comprobante)
        End Function
        
        Public Function TimbrarAckBase64(ByVal comprobante As String) As WebServicesCFDI.TimbradoReference.TimbradoCFDIResult Implements DigitalInvoiceC.ITimbrado.TimbrarAckBase64
            Return MyBase.Channel.TimbrarAckBase64(comprobante)
        End Function
        
        Public Function RecuperarTimbreBase64(ByVal comprobante As String) As String Implements DigitalInvoiceC.ITimbrado.RecuperarTimbreBase64
            Return MyBase.Channel.RecuperarTimbreBase64(comprobante)
        End Function
        
        Public Function RecuperarTimbreBase64UUID(ByVal UUID As String) As String Implements DigitalInvoiceC.ITimbrado.RecuperarTimbreBase64UUID
            Return MyBase.Channel.RecuperarTimbreBase64UUID(UUID)
        End Function
        
        Public Function RecuperarTimbresBase64(ByVal UUIDs() As String) As String() Implements DigitalInvoiceC.ITimbrado.RecuperarTimbresBase64
            Return MyBase.Channel.RecuperarTimbresBase64(UUIDs)
        End Function
        
        Public Function TimbrarSoloTimbreBase64(ByVal comprobante As String) As String Implements DigitalInvoiceC.ITimbrado.TimbrarSoloTimbreBase64
            Return MyBase.Channel.TimbrarSoloTimbreBase64(comprobante)
        End Function
    End Class
End Namespace
