//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaVendedor
    {
        public string DiaClave { get; set; }
        public string VendedorId { get; set; }
        public string FrecuenciaClave { get; set; }
        public string RUTClave { get; set; }
        public int Orden { get; set; }
        public string ClienteClave { get; set; }
        public string ClaveCEDI { get; set; }
        public Nullable<short> TipoMotivo { get; set; }
        public string Comentario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual Frecuencia Frecuencia { get; set; }
        public virtual Ruta Ruta { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
