//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public string RECId { get; set; }
        public short Tipo { get; set; }
        public short TipoEstado { get; set; }
        public bool Predeterminado { get; set; }
        public short TipoPapel { get; set; }
        public bool AgruparPorPrecio { get; set; }
        public bool MostrarLogo { get; set; }
        public bool MostrarEquivalencia { get; set; }
        public bool MostrarKilos { get; set; }
        public bool AgruparPorSubem { get; set; }
        public string CORId { get; set; }
        public string COTId { get; set; }
        public string COCId { get; set; }
        public bool IncluirImpuestos { get; set; }
        public bool MostrarCodBarras { get; set; }
        public bool SeccionProdPromo { get; set; }
        public short MostrarTotalUnidades { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioID { get; set; }
        public short LeyendaFacturar { get; set; }
    
        public virtual COTCampo COTCampo { get; set; }
    }
}
