insert into documentostipo values ('P', rtrim('7   '), ltrim(rtrim('      ABONO A CHEQUE')), 'A', 'A')
insert into documentostipo values ('AN', rtrim('17  '), ltrim(rtrim('     ANTICIPO')), 'A', 'A')
insert into documentostipo values ('AN', rtrim('18  '), ltrim(rtrim('     APLICACIÓN DE ANTICIPO')), 'A', 'A')
insert into documentostipo values ('DEV', rtrim('62  '), ltrim(rtrim('     DEVOLUCIONES')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('21  '), ltrim(rtrim('     N.CDTO A CLIENTE POR PROMOCION')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('78  '), ltrim(rtrim('     N.CDTO A CLIENTE POR EXCLUSIVA')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('65  '), ltrim(rtrim('     N.CDTO A CLIENTE POR PROMOCION(MANUAL)')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('32  '), ltrim(rtrim('     N.CDTO A CLIENTE 1/10 TAMPICO')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('25  '), ltrim(rtrim('     N.CDTO A CLIENTE POR DONATIVO')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('28  '), ltrim(rtrim('     N.CDTO A DISTRIBUIDOR')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('63  '), ltrim(rtrim('     N.CDTO CONVENIO ESPECIAL')), 'A', 'A')
insert into documentostipo values ('P', rtrim('64  '), ltrim(rtrim('    PAGO POR  TRANSFERENCIA')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('72  '), ltrim(rtrim('     N.CDTO POR APERTURA  DE TIENDA')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('73  '), ltrim(rtrim('     N.CDTO POR APORTACION ANUAL')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('74  '), ltrim(rtrim('     N.CDTO POR APORTACION NAVIDEÑA')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('70  '), ltrim(rtrim('     N.CDTO POR APOYO A REFRIGERACION ')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('71  '), ltrim(rtrim('     N.CDTO POR APOYO ESPACIOS EN EXHIBICION')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('76  '), ltrim(rtrim('     N.CDTO POR SERVICIOS DE INTERNERT')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('47  '), ltrim(rtrim('     N CDTO PRORROGA CAMBIO DE PRECIO')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('3   '), ltrim(rtrim('     N. CDTO A CLIENTE POR DIFERENCIA EN PAGO')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('6   '), ltrim(rtrim('     N. CARGO A DISTRIBUIDOR')), 'A', 'A')
insert into documentostipo values ('NR', rtrim('19  '), ltrim(rtrim('    N. CDTO A CLIENTE POR FALTANTE')), 'A', 'A')
