'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace DigitalInvoiceWS33
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CFDiFaultContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProcessFaultContract
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProcessField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Process() As String
            Get
                Return Me.ProcessField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProcessField, value) <> true) Then
                    Me.ProcessField = value
                    Me.RaisePropertyChanged("Process")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TimbradoCFDIResult", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.WebServices.WSDI"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TimbradoCFDIResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AcknowledgeBase64Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ComprobanteField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AcknowledgeBase64() As String
            Get
                Return Me.AcknowledgeBase64Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AcknowledgeBase64Field, value) <> true) Then
                    Me.AcknowledgeBase64Field = value
                    Me.RaisePropertyChanged("AcknowledgeBase64")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Comprobante() As Byte()
            Get
                Return Me.ComprobanteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ComprobanteField, value) <> true) Then
                    Me.ComprobanteField = value
                    Me.RaisePropertyChanged("Comprobante")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://digitalinvoice.com.mx/WSDI", ConfigurationName:="DigitalInvoiceWS33.ITimbrado")>  _
    Public Interface ITimbrado
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/Timbrar", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function Timbrar(ByVal comprobanteBytesZipped() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/Timbrar", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarResponse")>  _
        Function TimbrarAsync(ByVal comprobanteBytesZipped() As Byte) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbre", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbre(ByVal comprobante() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbre", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreResponse")>  _
        Function TimbrarSoloTimbreAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTest", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarTest(ByVal comprobanteBytesZipped() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTest", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestResponse")>  _
        Function TimbrarTestAsync(ByVal comprobanteBytesZipped() As Byte) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTest", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbreTest(ByVal comprobante() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTest", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestResponse")>  _
        Function TimbrarSoloTimbreTestAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAck", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarAck(ByVal comprobante() As Byte) As DigitalInvoiceWS33.TimbradoCFDIResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAck", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckResponse")>  _
        Function TimbrarAckAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of DigitalInvoiceWS33.TimbradoCFDIResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/ObtenerAck", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/ObtenerAckResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function ObtenerAck(ByVal UUID As String, ByVal rfcEmisor As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/ObtenerAck", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/ObtenerAckResponse")>  _
        Function ObtenerAckAsync(ByVal UUID As String, ByVal rfcEmisor As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbre", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbre(ByVal comprobante() As Byte) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbre", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreResponse")>  _
        Function RecuperarTimbreAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreUUID", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreUUIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbreUUID(ByVal UUID As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreUUID", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreUUIDResponse")>  _
        Function RecuperarTimbreUUIDAsync(ByVal UUID As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbres", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbres(ByVal UUIDs() As String) As Byte()()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbres", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresResponse")>  _
        Function RecuperarTimbresAsync(ByVal UUIDs() As String) As System.Threading.Tasks.Task(Of Byte()())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarBase64Response")>  _
        Function TimbrarBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarTestBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarTestBase64Response")>  _
        Function TimbrarTestBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbreTestBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreTestBase64Response")>  _
        Function TimbrarSoloTimbreTestBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarAckBase64(ByVal comprobante As String) As DigitalInvoiceWS33.TimbradoCFDIResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarAckBase64Response")>  _
        Function TimbrarAckBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of DigitalInvoiceWS33.TimbradoCFDIResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbreBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64Response")>  _
        Function RecuperarTimbreBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64UUID", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64UUIDResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbreBase64UUID(ByVal UUID As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64UUID", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbreBase64UUIDResponse")>  _
        Function RecuperarTimbreBase64UUIDAsync(ByVal UUID As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function RecuperarTimbresBase64(ByVal UUIDs() As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/RecuperarTimbresBase64Response")>  _
        Function RecuperarTimbresBase64Async(ByVal UUIDs() As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreBase64Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.CFDiFaultContract), Action:="http://digitalinvoice.com.mx/CFDiFaultContract", Name:="CFDiFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions"),  _
         System.ServiceModel.FaultContractAttribute(GetType(DigitalInvoiceWS33.ProcessFaultContract), Action:="http://digitalinvoice.com.mx/ProcessFaultContract", Name:="ProcessFaultContract", [Namespace]:="http://schemas.datacontract.org/2004/07/DigitalInvoice.Processes.Exceptions")>  _
        Function TimbrarSoloTimbreBase64(ByVal comprobante As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreBase64", ReplyAction:="https://digitalinvoice.com.mx/WSDI/ITimbrado/TimbrarSoloTimbreBase64Response")>  _
        Function TimbrarSoloTimbreBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITimbradoChannel
        Inherits DigitalInvoiceWS33.ITimbrado, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TimbradoClient
        Inherits System.ServiceModel.ClientBase(Of DigitalInvoiceWS33.ITimbrado)
        Implements DigitalInvoiceWS33.ITimbrado
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Timbrar(ByVal comprobanteBytesZipped() As Byte) As Byte() Implements DigitalInvoiceWS33.ITimbrado.Timbrar
            Return MyBase.Channel.Timbrar(comprobanteBytesZipped)
        End Function
        
        Public Function TimbrarAsync(ByVal comprobanteBytesZipped() As Byte) As System.Threading.Tasks.Task(Of Byte()) Implements DigitalInvoiceWS33.ITimbrado.TimbrarAsync
            Return MyBase.Channel.TimbrarAsync(comprobanteBytesZipped)
        End Function
        
        Public Function TimbrarSoloTimbre(ByVal comprobante() As Byte) As Byte() Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbre
            Return MyBase.Channel.TimbrarSoloTimbre(comprobante)
        End Function
        
        Public Function TimbrarSoloTimbreAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of Byte()) Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbreAsync
            Return MyBase.Channel.TimbrarSoloTimbreAsync(comprobante)
        End Function
        
        Public Function TimbrarTest(ByVal comprobanteBytesZipped() As Byte) As Byte() Implements DigitalInvoiceWS33.ITimbrado.TimbrarTest
            Return MyBase.Channel.TimbrarTest(comprobanteBytesZipped)
        End Function
        
        Public Function TimbrarTestAsync(ByVal comprobanteBytesZipped() As Byte) As System.Threading.Tasks.Task(Of Byte()) Implements DigitalInvoiceWS33.ITimbrado.TimbrarTestAsync
            Return MyBase.Channel.TimbrarTestAsync(comprobanteBytesZipped)
        End Function
        
        Public Function TimbrarSoloTimbreTest(ByVal comprobante() As Byte) As Byte() Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbreTest
            Return MyBase.Channel.TimbrarSoloTimbreTest(comprobante)
        End Function
        
        Public Function TimbrarSoloTimbreTestAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of Byte()) Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbreTestAsync
            Return MyBase.Channel.TimbrarSoloTimbreTestAsync(comprobante)
        End Function
        
        Public Function TimbrarAck(ByVal comprobante() As Byte) As DigitalInvoiceWS33.TimbradoCFDIResult Implements DigitalInvoiceWS33.ITimbrado.TimbrarAck
            Return MyBase.Channel.TimbrarAck(comprobante)
        End Function
        
        Public Function TimbrarAckAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of DigitalInvoiceWS33.TimbradoCFDIResult) Implements DigitalInvoiceWS33.ITimbrado.TimbrarAckAsync
            Return MyBase.Channel.TimbrarAckAsync(comprobante)
        End Function
        
        Public Function ObtenerAck(ByVal UUID As String, ByVal rfcEmisor As String) As String Implements DigitalInvoiceWS33.ITimbrado.ObtenerAck
            Return MyBase.Channel.ObtenerAck(UUID, rfcEmisor)
        End Function
        
        Public Function ObtenerAckAsync(ByVal UUID As String, ByVal rfcEmisor As String) As System.Threading.Tasks.Task(Of String) Implements DigitalInvoiceWS33.ITimbrado.ObtenerAckAsync
            Return MyBase.Channel.ObtenerAckAsync(UUID, rfcEmisor)
        End Function
        
        Public Function RecuperarTimbre(ByVal comprobante() As Byte) As Byte() Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbre
            Return MyBase.Channel.RecuperarTimbre(comprobante)
        End Function
        
        Public Function RecuperarTimbreAsync(ByVal comprobante() As Byte) As System.Threading.Tasks.Task(Of Byte()) Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbreAsync
            Return MyBase.Channel.RecuperarTimbreAsync(comprobante)
        End Function
        
        Public Function RecuperarTimbreUUID(ByVal UUID As String) As Byte() Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbreUUID
            Return MyBase.Channel.RecuperarTimbreUUID(UUID)
        End Function
        
        Public Function RecuperarTimbreUUIDAsync(ByVal UUID As String) As System.Threading.Tasks.Task(Of Byte()) Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbreUUIDAsync
            Return MyBase.Channel.RecuperarTimbreUUIDAsync(UUID)
        End Function
        
        Public Function RecuperarTimbres(ByVal UUIDs() As String) As Byte()() Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbres
            Return MyBase.Channel.RecuperarTimbres(UUIDs)
        End Function
        
        Public Function RecuperarTimbresAsync(ByVal UUIDs() As String) As System.Threading.Tasks.Task(Of Byte()()) Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbresAsync
            Return MyBase.Channel.RecuperarTimbresAsync(UUIDs)
        End Function
        
        Public Function TimbrarBase64(ByVal comprobante As String) As String Implements DigitalInvoiceWS33.ITimbrado.TimbrarBase64
            Return MyBase.Channel.TimbrarBase64(comprobante)
        End Function
        
        Public Function TimbrarBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String) Implements DigitalInvoiceWS33.ITimbrado.TimbrarBase64Async
            Return MyBase.Channel.TimbrarBase64Async(comprobante)
        End Function
        
        Public Function TimbrarTestBase64(ByVal comprobante As String) As String Implements DigitalInvoiceWS33.ITimbrado.TimbrarTestBase64
            Return MyBase.Channel.TimbrarTestBase64(comprobante)
        End Function
        
        Public Function TimbrarTestBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String) Implements DigitalInvoiceWS33.ITimbrado.TimbrarTestBase64Async
            Return MyBase.Channel.TimbrarTestBase64Async(comprobante)
        End Function
        
        Public Function TimbrarSoloTimbreTestBase64(ByVal comprobante As String) As String Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbreTestBase64
            Return MyBase.Channel.TimbrarSoloTimbreTestBase64(comprobante)
        End Function
        
        Public Function TimbrarSoloTimbreTestBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String) Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbreTestBase64Async
            Return MyBase.Channel.TimbrarSoloTimbreTestBase64Async(comprobante)
        End Function
        
        Public Function TimbrarAckBase64(ByVal comprobante As String) As DigitalInvoiceWS33.TimbradoCFDIResult Implements DigitalInvoiceWS33.ITimbrado.TimbrarAckBase64
            Return MyBase.Channel.TimbrarAckBase64(comprobante)
        End Function
        
        Public Function TimbrarAckBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of DigitalInvoiceWS33.TimbradoCFDIResult) Implements DigitalInvoiceWS33.ITimbrado.TimbrarAckBase64Async
            Return MyBase.Channel.TimbrarAckBase64Async(comprobante)
        End Function
        
        Public Function RecuperarTimbreBase64(ByVal comprobante As String) As String Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbreBase64
            Return MyBase.Channel.RecuperarTimbreBase64(comprobante)
        End Function
        
        Public Function RecuperarTimbreBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String) Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbreBase64Async
            Return MyBase.Channel.RecuperarTimbreBase64Async(comprobante)
        End Function
        
        Public Function RecuperarTimbreBase64UUID(ByVal UUID As String) As String Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbreBase64UUID
            Return MyBase.Channel.RecuperarTimbreBase64UUID(UUID)
        End Function
        
        Public Function RecuperarTimbreBase64UUIDAsync(ByVal UUID As String) As System.Threading.Tasks.Task(Of String) Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbreBase64UUIDAsync
            Return MyBase.Channel.RecuperarTimbreBase64UUIDAsync(UUID)
        End Function
        
        Public Function RecuperarTimbresBase64(ByVal UUIDs() As String) As String() Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbresBase64
            Return MyBase.Channel.RecuperarTimbresBase64(UUIDs)
        End Function
        
        Public Function RecuperarTimbresBase64Async(ByVal UUIDs() As String) As System.Threading.Tasks.Task(Of String()) Implements DigitalInvoiceWS33.ITimbrado.RecuperarTimbresBase64Async
            Return MyBase.Channel.RecuperarTimbresBase64Async(UUIDs)
        End Function
        
        Public Function TimbrarSoloTimbreBase64(ByVal comprobante As String) As String Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbreBase64
            Return MyBase.Channel.TimbrarSoloTimbreBase64(comprobante)
        End Function
        
        Public Function TimbrarSoloTimbreBase64Async(ByVal comprobante As String) As System.Threading.Tasks.Task(Of String) Implements DigitalInvoiceWS33.ITimbrado.TimbrarSoloTimbreBase64Async
            Return MyBase.Channel.TimbrarSoloTimbreBase64Async(comprobante)
        End Function
    End Class
End Namespace
